// Created with resguy v6 (November 2017)
// https://github.com/wootguy/resguy

gfx/env/asciiartbk.tga
gfx/env/asciiartdn.tga
gfx/env/asciiartft.tga
gfx/env/asciiartlf.tga
gfx/env/asciiartrt.tga
gfx/env/asciiartup.tga
models/player/aan/aan.bmp
models/player/aan/aan.mdl
models/player/uboa/uboa.bmp
models/player/uboa/uboa.mdl
models/player/uboa2/uboa2.bmp
models/player/uboa2/uboa2.mdl
models/player/uboa2b/uboa2b.bmp
models/player/uboa2b/uboa2b.mdl
models/player/uboab/uboab.bmp
models/player/uboab/uboab.mdl
models/uboa/babygarg.mdl
models/uboa/babygargt.mdl
models/uboa/bluemassn.mdl
models/uboa/greenmassn.mdl
models/uboa/greymassn.mdl
models/uboa/kintama.mdl
models/uboa/kintamat.mdl
models/uboa/konichiwa.mdl
models/uboa/moripo.mdl
models/uboa/mrkimo.mdl
models/uboa/mrkimot.mdl
models/uboa/overmk2.mdl
models/uboa/redmassn.mdl
models/uboa/uboablack.mdl
models/uboa/uboawhite.mdl
models/uboa/uboazombie.mdl
models/uboa/uboazombie01.mdl
models/uboa/uboazombie02.mdl
models/uboa/uboazombie03.mdl
models/uboa/uboazombieT.mdl
models/uboa/yellowmassn.mdl
sound/uboa/ac.wav
sound/uboa/gj.wav
sound/uboa/konichiwa/attack.wav
sound/uboa/konichiwa/konichiwa.wav
sound/uboa/konichiwa/konichiwa2.wav
sound/uboa/konichiwa/konichiwa3.wav
sound/uboa/konichiwa/miss.wav
sound/uboa/moripo/ara.wav
sound/uboa/moripo/ara2.wav
sound/uboa/moripo/ara3.wav
sound/uboa/uboazombie/zo_pain1.wav
sound/uboa/uboazombie/zo_pain2.wav
sound/uboa/zkare.wav
