// Created with resguy v7 (December 2017)
// https://github.com/wootguy/resguy

asheep.wad
models/azuresheep/p_9mmberetta.mdl
models/azuresheep/p_9mmm41a.mdl
models/azuresheep/p_chub.mdl
models/azuresheep/p_crowbar.mdl
models/azuresheep/p_kmedkit.mdl
models/azuresheep/p_poolstick.mdl
models/azuresheep/v_357.mdl
models/azuresheep/v_9mmberetta.mdl
models/azuresheep/v_9mmm41a.mdl
models/azuresheep/v_barney9mmar.mdl
models/azuresheep/v_barney9mmhg.mdl
models/azuresheep/v_barneygrenade.mdl
models/azuresheep/v_barneyshotgun.mdl
models/azuresheep/v_crossbow.mdl
models/azuresheep/v_crowbar.mdl
models/azuresheep/v_egon.mdl
models/azuresheep/v_gauss.mdl
models/azuresheep/v_kmedkit.mdl
models/azuresheep/v_poolstick.mdl
models/azuresheep/v_rpg.mdl
models/azuresheep/v_satchel.mdl
models/azuresheep/v_satchel_radio.mdl
models/azuresheep/v_toad.mdl
models/azuresheep/v_tripmine.mdl
models/azuresheep/w_9mmberetta.mdl
models/azuresheep/w_9mmm41a.mdl
models/azuresheep/w_blue_suit.mdl
models/azuresheep/w_blue_suitt.mdl
models/azuresheep/w_chub.mdl
models/azuresheep/w_crowbar.mdl
models/azuresheep/w_crowbart.mdl
models/azuresheep/w_kmedkit.mdl
models/azuresheep/w_kmedkitt.mdl
models/azuresheep/w_poolstick.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/hl/p_357.mdl
models/hl/v_357.mdl
models/hl/w_357.mdl
models/hl/w_357t.mdl
sound/ambience/flareidle.wav
sound/barney/goon.wav
sound/barniel/_comma.wav
sound/barniel/aimforhead.wav
sound/barniel/badfeeling.wav
sound/barniel/bequiet.wav
sound/barniel/bn_another.wav
sound/barniel/bn_attack1.wav
sound/barniel/bn_becarefull.wav
sound/barniel/bn_bring.wav
sound/barniel/bn_carefull.wav
sound/barniel/bn_close.wav
sound/barniel/bn_die1.wav
sound/barniel/bn_dontdothat.wav
sound/barniel/bn_dontmake.wav
sound/barniel/bn_endline.wav
sound/barniel/bn_firepl.wav
sound/barniel/bn_friends.wav
sound/barniel/bn_gotone.wav
sound/barniel/bn_iwish.wav
sound/barniel/bn_onelessh.wav
sound/barniel/bn_post.wav
sound/barniel/bn_seethat.wav
sound/barniel/bn_somuch.wav
sound/barniel/bn_stepoff.wav
sound/barniel/bn_tomb.wav
sound/barniel/bn_uwish.wav
sound/barniel/bn_whatyou.wav
sound/barniel/diegreenthing.wav
sound/barniel/dontagree.wav
sound/barniel/dontknow.wav
sound/barniel/drinktopside.wav
sound/barniel/hearsomething.wav
sound/barniel/hevno.wav
sound/barniel/hi.wav
sound/barniel/hitbad.wav
sound/barniel/humm.wav
sound/barniel/imhit.wav
sound/barniel/movietv.wav
sound/barniel/nosir.wav
sound/barniel/openfire.wav
sound/barniel/rightway.wav
sound/barniel/seelater.wav
sound/barniel/seeya.wav
sound/barniel/slimything.wav
sound/barniel/somethingmoves.wav
sound/barniel/stop1.wav
sound/barniel/teamup1.wav
sound/barniel/teamup2.wav
sound/barniel/thinking.wav
sound/barniel/waitin.wav
sound/barniel/whatsgoingon.wav
sound/barniel/yessir.wav
sound/barniel/youneedmedic.wav
sound/fvox/health_kate.wav
sound/girl/hctroub.wav
sound/gordon/aimforhead.wav
sound/gordon/aintscared.wav
sound/gordon/ambush.wav
sound/gordon/bigmess.wav
sound/gordon/checkwounds.wav
sound/gordon/diebloodsucker.wav
sound/gordon/dobettertogether.wav
sound/gordon/dontbet.wav
sound/gordon/donthurtem.wav
sound/gordon/getanyworse.wav
sound/gordon/gladof38.wav
sound/gordon/gladtolendhand.wav
sound/gordon/go_another.wav
sound/gordon/go_bring.wav
sound/gordon/go_buttugly.wav
sound/gordon/go_close.wav
sound/gordon/go_dontmake.wav
sound/gordon/go_dotoyou.wav
sound/gordon/go_endline.wav
sound/gordon/go_firepl.wav
sound/gordon/go_friends.wav
sound/gordon/go_gotone.wav
sound/gordon/go_iwish.wav
sound/gordon/go_pain2.wav
sound/gordon/go_seethat.wav
sound/gordon/go_somuch.wav
sound/gordon/go_stepoff.wav
sound/gordon/go_tomb.wav
sound/gordon/go_uwish.wav
sound/gordon/go_watchit.wav
sound/gordon/go_whatyou.wav
sound/gordon/go_whoathere.wav
sound/gordon/hearsomething.wav
sound/gordon/hearsomething2.wav
sound/gordon/hellonicesuit.wav
sound/gordon/hitbad.wav
sound/gordon/imdead.wav
sound/gordon/imhit.wav
sound/gordon/leavealone.wav
sound/gordon/luckwillturn.wav
sound/gordon/noway.wav
sound/gordon/seeya.wav
sound/gordon/slowingyoudown.wav
sound/gordon/somethingdied.wav
sound/gordon/somethingmoves.wav
sound/gordon/soundsright.wav
sound/gordon/standback.wav
sound/gordon/standguard.wav
sound/gordon/stench.wav
sound/gordon/stop1.wav
sound/gordon/stop2.wav
sound/gordon/targetpractice.wav
sound/gordon/teamup1.wav
sound/gordon/yougotit.wav
sound/gordon/youhearthat.wav
sound/gordon/youneedmedic.wav
sound/gordon/yup.wav
sound/hl/weapons/357_reload1.wav
sound/hl/weapons/357_shot1.wav
sound/hl/weapons/357_shot2.wav
sound/kate/aimforhead.wav
sound/kate/anotherdown.wav
sound/kate/badfelling.wav
sound/kate/becarefull.wav
sound/kate/bequiet.wav
sound/kate/bigeye.wav
sound/kate/bringitone.wav
sound/kate/close.wav
sound/kate/correctway.wav
sound/kate/cupoftie.wav
sound/kate/didntwantthis.wav
sound/kate/didseeshot.wav
sound/kate/dieslimy.wav
sound/kate/dinnerend.wav
sound/kate/dontagree.wav
sound/kate/dontdothat.wav
sound/kate/dontdothis.wav
sound/kate/dontknow.wav
sound/kate/dontwantlive.wav
sound/kate/freebarney.wav
sound/kate/friendslikeyou.wav
sound/kate/gotanother.wav
sound/kate/gotone.wav
sound/kate/hearsomething.wav
sound/kate/hevno.wav
sound/kate/hi.wav
sound/kate/hitbad.wav
sound/kate/hitbad2.wav
sound/kate/hoyes.wav
sound/kate/hummm.wav
sound/kate/iamkate.wav
sound/kate/ka_attack1.wav
sound/kate/muchmore.wav
sound/kate/notatall.wav
sound/kate/oneless.wav
sound/kate/openfire.wav
sound/kate/resquedatlast.wav
sound/kate/seelater.wav
sound/kate/seeyoulater.wav
sound/kate/somethingmove.wav
sound/kate/staypost.wav
sound/kate/stepoff.wav
sound/kate/stop1.wav
sound/kate/teamup1.wav
sound/kate/teamup2.wav
sound/kate/thinking.wav
sound/kate/waithere.wav
sound/kate/waithere2.wav
sound/kate/welcome.wav
sound/kate/whatgoingon.wav
sound/kate/whatgoingon2.wav
sound/kate/whatyoudoing.wav
sound/kate/yesbarn.wav
sound/kate/youaredead.wav
sound/kate/youneedmedic.wav
sound/kate/youwish.wav
sound/plats/theli1.wav
sound/player/heart1.wav
sound/scientist/noopen.wav
sound/scientist/sci_alone2.wav
sound/scientist/wareh.wav
sound/weapons/kmedkit_sayhealth.wav
sprites/hl_weapons/weapon_hl357.txt
