// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

models/ast/detpack.mdl
models/ast/hwagrunt.mdl
models/ast/scientist_armed.mdl
models/decay/dead_islave.mdl
models/decay/health_charger_body.mdl
models/decay/health_charger_both.mdl
models/decay/tank_base.mdl
models/opfor/svenhands/v_knife.mdl
models/opfor/wire_black32.mdl
models/opfor/wire_copper8.mdl
models/scmod/ast/weapons/p_357.mdl
models/scmod/ast/weapons/p_9mmar.mdl
models/scmod/ast/weapons/p_9mmhandgun.mdl
models/scmod/ast/weapons/p_crowbar.mdl
models/scmod/ast/weapons/p_desert_eagle.mdl
models/scmod/ast/weapons/p_grenade.mdl
models/scmod/ast/weapons/p_m16.mdl
models/scmod/ast/weapons/p_m40a1.mdl
models/scmod/ast/weapons/p_saw.mdl
models/scmod/ast/weapons/v_357.mdl
models/scmod/ast/weapons/v_9mmar.mdl
models/scmod/ast/weapons/v_9mmhandgun.mdl
models/scmod/ast/weapons/v_crowbar.mdl
models/scmod/ast/weapons/v_desert_eagle.mdl
models/scmod/ast/weapons/v_grenade.mdl
models/scmod/ast/weapons/v_m16a2.mdl
models/scmod/ast/weapons/v_m40a1.mdl
models/scmod/ast/weapons/v_saw.mdl
models/scmod/ast/weapons/w_357.mdl
models/scmod/ast/weapons/w_9mmar.mdl
models/scmod/ast/weapons/w_9mmarclip.mdl
models/scmod/ast/weapons/w_9mmclip.mdl
models/scmod/ast/weapons/w_9mmhandgun.mdl
models/scmod/ast/weapons/w_crowbar.mdl
models/scmod/ast/weapons/w_desert_eagle.mdl
models/scmod/ast/weapons/w_grenade.mdl
models/scmod/ast/weapons/w_m16.mdl
models/scmod/ast/weapons/w_m40a1.mdl
models/scmod/ast/weapons/w_mp5_clip.mdl
models/scmod/ast/weapons/w_saw.mdl
models/scmod/ast/weapons/w_saw_clip.mdl
models/scmod/item_canister.mdl
models/scmod/item_detpack.mdl
models/scmod/item_security.mdl
models/scmod/item_skull.mdl
models/scmod/keycard_panel_classic.mdl
models/scmod/mduty/apc_turret2.mdl
models/scmod/npcs/barnotis/war_nuker.mdl
models/scmod/npcs/fassn/lyn.mdl
models/scmod/npcs/hgrunt/homosapien.mdl
models/scmod/npcs/hgrunt/marphyblack.mdl
models/scmod/npcs/hgrunt/pumpkin_masher.mdl
models/scmod/npcs/hgrunt/soulescape.mdl
models/scmod/npcs/massn/giygas.mdl
models/scmod/npcs/op4/gurluas.mdl
models/scmod/opbt/pit_drone_elite.mdl
models/scmod/opbt/strooper.mdl
models/scmod/opbt/strooper_orange.mdl
models/scmod/opbt/sventry.mdl
models/scmod/opbt/w_dispenser.mdl
models/scmod/opbt/w_dispenser_holo.mdl
models/scmod/phouse/sky_xen.mdl
models/scmod/sky/sky_xen2.mdl
sound/ast/detpack.wav
sound/ast/dialogs/ast_c04/radio_airstrike.ogg
sound/ast/dialogs/ast_c05/fireinthehole.ogg
sound/ast/dialogs/ast_c05/radio_delivery_fem.ogg
sound/ast/dialogs/ast_c05/radio_inposition_fem.ogg
sound/ast/dialogs/ast_c06/10soldiera.ogg
sound/ast/dialogs/ast_c06/1soldiera.ogg
sound/ast/dialogs/ast_c06/2soldierb.ogg
sound/ast/dialogs/ast_c06/3soldiera.ogg
sound/ast/dialogs/ast_c06/4soldierb.ogg
sound/ast/dialogs/ast_c06/5soldierc.ogg
sound/ast/dialogs/ast_c06/6soldierb.ogg
sound/ast/dialogs/ast_c06/7soldierc.ogg
sound/ast/dialogs/ast_c06/8soldiera.ogg
sound/ast/dialogs/ast_c06/9soldierb.ogg
sound/ast/dialogs/ast_c06/overhere.ogg
sound/ast/dialogs/ast_c07/1marphy.ogg
sound/ast/forgetfreeman.ogg
sound/ast/nukeexplosion.ogg
sound/ast/opfor10_sci_portal.wav
sound/ast/opfor10_sci_portopen.wav
sound/ast/rocketfight.ogg
sound/ast/vivaldiref.ogg
sound/scmod/npcs/betapitdrone/pit_drone_alert1.wav
sound/scmod/npcs/betapitdrone/pit_drone_alert2.wav
sound/scmod/npcs/betapitdrone/pit_drone_alert3.wav
sound/scmod/npcs/betapitdrone/pit_drone_attack_spike1.wav
sound/scmod/npcs/betapitdrone/pit_drone_attack_spike2.wav
sound/scmod/npcs/betapitdrone/pit_drone_communicate1.wav
sound/scmod/npcs/betapitdrone/pit_drone_communicate2.wav
sound/scmod/npcs/betapitdrone/pit_drone_communicate3.wav
sound/scmod/npcs/betapitdrone/pit_drone_communicate4.wav
sound/scmod/npcs/betapitdrone/pit_drone_die1.wav
sound/scmod/npcs/betapitdrone/pit_drone_die2.wav
sound/scmod/npcs/betapitdrone/pit_drone_die3.wav
sound/scmod/npcs/betapitdrone/pit_drone_hunt1.wav
sound/scmod/npcs/betapitdrone/pit_drone_hunt2.wav
sound/scmod/npcs/betapitdrone/pit_drone_hunt3.wav
sound/scmod/npcs/betapitdrone/pit_drone_idle1.wav
sound/scmod/npcs/betapitdrone/pit_drone_idle2.wav
sound/scmod/npcs/betapitdrone/pit_drone_idle3.wav
sound/scmod/npcs/betapitdrone/pit_drone_melee_attack1.wav
sound/scmod/npcs/betapitdrone/pit_drone_melee_attack2.wav
sound/scmod/npcs/betapitdrone/pit_drone_pain1.wav
sound/scmod/npcs/betapitdrone/pit_drone_pain2.wav
sound/scmod/npcs/betapitdrone/pit_drone_pain3.wav
sound/scmod/npcs/betapitdrone/pit_drone_pain4.wav
sound/shl/m41a_3round.wav
sound/shl/m41aglauncher.wav
sound/weapons/629_shells_land.wav
sound/weapons/cs/awp_clipin.wav
sound/weapons/cs/awp_clipout.wav
sound/weapons/cs/boltdown.wav
sound/weapons/cs/boltpull1.wav
sound/weapons/cs/boltup.wav
sound/weapons/knife_deploy1.wav
sound/weapons/m4_boltback.wav
sound/weapons/m4_boltrelease.wav
sound/weapons/m4_magin.wav
sound/weapons/m4_magout.wav
sound/weapons/revolvers_bulletsin.wav
sound/weapons/revolvers_rod.wav
sound/weapons/revolvers_wheelin.wav
sound/weapons/revolvers_wheelout.wav
sound/weapons/ump45_magin.wav
sound/weapons/ump45_magout.wav
sound/weapons/usp_drawcock.wav
sound/weapons/usp_magin.wav
sound/weapons/usp_magout.wav
sound/weapons/usp_pickup.wav
sound/weapons/usp_slideback.wav
sprites/opfor/weapon_knife.txt
sprites/scmod/item_keycard.spr
