// Created with resguy v6 (November 2017)
// https://github.com/wootguy/resguy

botparty.wad
gfx/env/sky35bk.tga
gfx/env/sky35dn.tga
gfx/env/sky35ft.tga
gfx/env/sky35lf.tga
gfx/env/sky35rt.tga
gfx/env/sky35up.tga
models/sc_royals/palm1a.mdl
models/sc_royals/palm1b.mdl
models/w00tguy/botparty/melon.mdl
models/w00tguy/botparty/watermelon.mdl
sound/w00tguy/botparty/all_win.ogg
sound/w00tguy/botparty/blue.wav
sound/w00tguy/botparty/box.ogg
sound/w00tguy/botparty/bumper.ogg
sound/w00tguy/botparty/chance.ogg
sound/w00tguy/botparty/dicebreak.wav
sound/w00tguy/botparty/draw.ogg
sound/w00tguy/botparty/escape.ogg
sound/w00tguy/botparty/finish.ogg
sound/w00tguy/botparty/green.wav
sound/w00tguy/botparty/island.ogg
sound/w00tguy/botparty/lose.ogg
sound/w00tguy/botparty/miss.ogg
sound/w00tguy/botparty/plat.ogg
sound/w00tguy/botparty/prize.ogg
sound/w00tguy/botparty/race.ogg
sound/w00tguy/botparty/red.wav
sound/w00tguy/botparty/results.ogg
sound/w00tguy/botparty/roller_select.ogg
sound/w00tguy/botparty/roller_tic.wav
sound/w00tguy/botparty/sea.ogg
sound/w00tguy/botparty/shroom.ogg
sound/w00tguy/botparty/space.wav
sound/w00tguy/botparty/start.ogg
sound/w00tguy/botparty/superstar.ogg
sound/w00tguy/botparty/timeout.ogg
sound/w00tguy/botparty/timeout_music.ogg
sound/w00tguy/botparty/tor.ogg
sound/w00tguy/botparty/winner.ogg
sprites/w00tguy/botparty/m25.spr
sprites/w00tguy/botparty/m5.spr
sprites/w00tguy/botparty/p10.spr
sprites/w00tguy/botparty/p25.spr
sprites/w00tguy/botparty/p5.spr
sprites/w00tguy/botparty/win.spr
