maps/deluge_beta_v3.res
maps/deluge_beta_v3.cfg
maps/deluge_beta_v3.gmr
maps/deluge_beta_v3_skl.cfg
maps/deluge_beta_v3_motd.txt
maps/deluge_beta.gsr

sound/rng/morass_beta/morass_special_v3.txt
sound/rng/morass_beta/morass_special2_v3.txt

sound/rng/deluge/weapons/car_bolt.ogg
sound/rng/deluge/weapons/car_clipin.ogg
sound/rng/deluge/weapons/car_clipout.ogg
sound/rng/deluge/weapons/car_draw.ogg
sound/rng/deluge/weapons_v3/car_fire.ogg
sound/rng/deluge/weapons/gundor_draw.ogg
sound/rng/deluge/weapons/gundor_fire.wav
sound/rng/deluge/weapons/gundor_idle.ogg
sound/rng/deluge/weapons/gundor_off.ogg
sound/rng/deluge/weapons/gundor_on.ogg
sound/rng/deluge/weapons/mag_clipin.ogg
sound/rng/deluge/weapons/mag_clipout.ogg
sound/rng/deluge/weapons/mag_draw.ogg
sound/rng/deluge/weapons_v3/mag_fire.ogg
sound/rng/deluge/weapons/mag_slide.ogg
sound/rng/deluge/weapons/mgun_ammobelt.ogg
sound/rng/deluge/weapons/mgun_ammobeltoff.ogg
sound/rng/deluge/weapons/mgun_bolt.ogg
sound/rng/deluge/weapons/mgun_clipin.ogg
sound/rng/deluge/weapons/mgun_clipout.ogg
sound/rng/deluge/weapons/mgun_close.ogg
sound/rng/deluge/weapons/mgun_draw.ogg
sound/rng/deluge/weapons_v3/mgun_fire.ogg
sound/rng/deluge/weapons/mgun_open.ogg
sound/rng/deluge/weapons/propulsion_draw.ogg
sound/rng/deluge/weapons_v3/propulsion_fire.ogg
sound/rng/deluge/weapons_v3/propulsion_fire2.ogg
sound/rng/deluge/weapons/propulsion_spin.ogg
sound/rng/deluge/weapons/propulsion_spinup.ogg
sound/rng/deluge/weapons/propulsion_zap1.ogg
sound/rng/deluge/weapons/propulsion_zap2.ogg
sound/rng/deluge/weapons/propulsion_zap3.ogg
sound/rng/deluge/weapons/rifle_bolt.ogg
sound/rng/deluge/weapons/rifle_clipin.ogg
sound/rng/deluge/weapons/rifle_clipout.ogg
sound/rng/deluge/weapons/rifle_draw.ogg
sound/rng/deluge/weapons_v3/rifle_fire.ogg
sound/rng/deluge/weapons/shotgun_draw.ogg
sound/rng/deluge/weapons_v3/shotgun_fire.ogg
sound/rng/deluge/weapons_v3/shotgun_fire2.ogg
sound/rng/deluge/weapons/shotgun_reload.ogg
sound/rng/deluge/weapons/smg_clipin.ogg
sound/rng/deluge/weapons/smg_clipout.ogg
sound/rng/deluge/weapons/smg_draw.ogg
sound/rng/deluge/weapons_v3/smg_fire.ogg
sound/rng/deluge/weapons/steampipe_draw.ogg
sound/rng/deluge/weapons/steampipe_hit.ogg
sound/rng/deluge/weapons/steampipe_hitflesh.ogg
sound/rng/deluge/weapons/steampipe_swing.ogg
sound/rng/deluge/weapons/vp_pistol_clipin.ogg
sound/rng/deluge/weapons/vp_pistol_clipout.ogg
sound/rng/deluge/weapons/vp_pistol_draw.ogg
sound/rng/deluge/weapons_v3/vp_pistol_fire.ogg
sound/rng/deluge/weapons_v3/vp_pistol_fire_empty.ogg
sound/rng/deluge/weapons/vp_pistol_slide.ogg
sound/rng/deluge/weapons/punch_miss.ogg
sound/rng/deluge/weapons/punch_hit.ogg
sound/rng/deluge/weapons/punch_hitbody.ogg
sound/rng/deluge/weapons/kick_miss.ogg
sound/rng/deluge/weapons/kick_hit.ogg
sound/rng/deluge/weapons/kick_hitbody.ogg
sound/rng/deluge/weapons/fists_draw.ogg

sound/rng/morass_beta/music_v3/mo1_v3_loop.ogg
sound/rng/morass_beta/music_v3/mo1_fight_v3_loop.ogg
sound/rng/morass_beta/music_v3/mo1_bossfight_v3_loop.ogg
sound/rng/morass_beta/music_v3/mo1_bossfight2_v3_loop.ogg
sound/rng/morass_beta/music_v3/loading_v3_loop.ogg
sound/rng/morass_beta/music_v3/mapend_v3_loop.ogg
sound/rng/morass_beta/music_v3/mapend_v3_outro.ogg
sound/rng/morass_beta/music_v3/mapendhard_v3_loop.ogg
sound/rng/morass_beta/music_v3/mapendhard_v3_outro.ogg
sound/rng/morass_beta/music_v3/mapenduv_v3_loop.ogg
sound/rng/morass_beta/music_v3/mapenduv_v3_outro.ogg

sound/rng/morass_beta/sounds/ammopickup.ogg
sound/rng/morass_beta/sounds/armorpickup.ogg
sound/rng/morass_beta/sounds/crane_crash.ogg
sound/rng/morass_beta/sounds/crane_move.ogg
sound/rng/morass_beta/sounds/crane_start.ogg
sound/rng/morass_beta/sounds/crane_stop.ogg
sound/rng/morass_beta/sounds/egonflash.ogg
sound/rng/morass_beta/sounds/ending_nextlevel.ogg
sound/rng/morass_beta/sounds/ending_start.ogg
sound/rng/morass_beta/sounds/ending_text.ogg
sound/rng/morass_beta/sounds/ending_textbird.ogg
sound/rng/morass_beta/sounds/ending_textkills.ogg
sound/rng/morass_beta/sounds/ending_textsecret.ogg
sound/rng/morass_beta/sounds/ending_textworm.ogg
sound/rng/morass_beta/sounds/ending_texthard.ogg
sound/rng/morass_beta/sounds/ending_textuv.ogg
sound/rng/morass_beta/sounds/ending_secretcounter.ogg
sound/rng/morass_beta/sounds/swampwall.ogg
sound/rng/morass_beta/sounds/gameover1.ogg
sound/rng/morass_beta/sounds/gameover2.ogg
sound/rng/morass_beta/sounds/gas.ogg
sound/rng/morass_beta/sounds/healthpickup.ogg
sound/rng/morass_beta/sounds/keypickup.ogg
sound/rng/morass_beta/sounds/loadscreen.ogg
sound/rng/morass_beta/sounds/newarea.ogg
sound/rng/morass_beta/sounds/null.wav
sound/rng/morass_beta/sounds/pillar_loop.ogg
sound/rng/morass_beta/sounds/pillarstart.ogg
sound/rng/morass_beta/sounds/pillarstop.ogg
sound/rng/morass_beta/sounds/secret.ogg
sound/rng/morass_beta/sounds/secret2.ogg
sound/rng/morass_beta/sounds/secret3.ogg
sound/rng/morass_beta/sounds/secret4.ogg
sound/rng/morass_beta/sounds/startscreen.ogg
sound/rng/morass_beta/sounds/wallbreak.ogg
sound/rng/morass_beta/sounds/weaponpickup_v3.ogg
sound/rng/morass_beta/sounds/break_flesh_v3.ogg
sound/rng/morass_beta/sounds/break_glass_v3.ogg
sound/rng/morass_beta/sounds/break_metal_v3.ogg
sound/rng/morass_beta/sounds/break_rock_v3.ogg
sound/rng/morass_beta/sounds/break_wood_v3.ogg
sound/rng/morass_beta/sounds/powerup.ogg
sound/rng/morass_beta/sounds/powerup2.ogg
sound/rng/morass_beta/sounds/powerup3.ogg
sound/rng/morass_beta/sounds/powerup_off.ogg
sound/rng/morass_beta/sounds/powerup_off2.ogg

sound/rng/morass_beta/sounds/ambient/comproom_loop.ogg
sound/rng/morass_beta/sounds/ambient/comproom2_loop.ogg
sound/rng/morass_beta/sounds/ambient/condor_loop.ogg
sound/rng/morass_beta/sounds/ambient/condor2_loop.ogg
sound/rng/morass_beta/sounds/ambient/craneroom_loop.ogg
sound/rng/morass_beta/sounds/ambient/greenroom_loop.ogg
sound/rng/morass_beta/sounds/ambient/largefan_loop.ogg
sound/rng/morass_beta/sounds/ambient/outside_loop.ogg
sound/rng/morass_beta/sounds/ambient/piperoom_loop.ogg
sound/rng/morass_beta/sounds/ambient/riftroom_loop.ogg
sound/rng/morass_beta/sounds/ambient/teleport_loop.ogg

sound/rng/morass_beta/sounds/doors/button1.ogg
sound/rng/morass_beta/sounds/doors/button2.ogg
sound/rng/morass_beta/sounds/doors/button3.ogg
sound/rng/morass_beta/sounds/doors/button4.ogg
sound/rng/morass_beta/sounds/doors/button5.ogg
sound/rng/morass_beta/sounds/doors/door1.ogg
sound/rng/morass_beta/sounds/doors/door2.ogg
sound/rng/morass_beta/sounds/doors/door3.ogg
sound/rng/morass_beta/sounds/doors/door4.ogg
sound/rng/morass_beta/sounds/doors/door5.ogg
sound/rng/morass_beta/sounds/doors/door6.ogg
sound/rng/morass_beta/sounds/doors/doorstop1.ogg
sound/rng/morass_beta/sounds/doors/doorstop2.ogg
sound/rng/morass_beta/sounds/doors/doorstop3.ogg
sound/rng/morass_beta/sounds/doors/doorstop4.ogg
sound/rng/morass_beta/sounds/doors/doorstop5.ogg
sound/rng/morass_beta/sounds/doors/doorstop6.ogg
sound/rng/morass_beta/sounds/doors/keylocked.ogg
sound/rng/morass_beta/sounds/doors/locked.ogg
sound/rng/morass_beta/sounds/doors/plat1.ogg
sound/rng/morass_beta/sounds/doors/plat2.ogg
sound/rng/morass_beta/sounds/doors/wheel.ogg

sound/rng/morass_beta/sounds/misc/dying.ogg
sound/rng/morass_beta/sounds/misc/gibbing.ogg
sound/rng/morass_beta/sounds/misc/medic.ogg
sound/rng/morass_beta/sounds/misc/takecover.ogg
sound/rng/morass_beta/sounds/misc/punch.ogg
sound/rng/morass_beta/sounds/misc/punch2.ogg
sound/rng/morass_beta/sounds/misc/punch3.ogg
sound/rng/morass_beta/sounds/misc/kick.ogg
sound/rng/morass_beta/sounds/misc/kick2.ogg
sound/rng/morass_beta/sounds/misc/roach_splat.ogg
sound/rng/morass_beta/sounds/misc/roach_die.ogg
sound/rng/morass_beta/sounds/misc/roach_walk.ogg

sound/rng/morass_beta/sounds/npc/armorman/armorman_alert.ogg
sound/rng/morass_beta/sounds/npc/armorman/armorman_alert2.ogg
sound/rng/morass_beta/sounds/npc/armorman/armorman_attack.ogg
sound/rng/morass_beta/sounds/npc/armorman/armorman_attack2.ogg
sound/rng/morass_beta/sounds/npc/armorman/armorman_die.ogg
sound/rng/morass_beta/sounds/npc/armorman/armorman_die2.ogg
sound/rng/morass_beta/sounds/npc/armorman/armorman_pain.ogg
sound/rng/morass_beta/sounds/npc/armorman/armorman_pain2.ogg
sound/rng/morass_beta/sounds/npc/armorman/armorman_pain3.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_attack.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_die.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_die2.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_pain.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_pain2.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_shoot.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_speak.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_speak2.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_speak3.ogg
sound/rng/morass_beta/sounds/npc/de_man/de_man_alert.ogg
sound/rng/morass_beta/sounds/npc/de_man/de_man_alert2.ogg
sound/rng/morass_beta/sounds/npc/de_man/de_man_attack.ogg
sound/rng/morass_beta/sounds/npc/de_man/de_man_attack2.ogg
sound/rng/morass_beta/sounds/npc/de_man/de_man_die.ogg
sound/rng/morass_beta/sounds/npc/de_man/de_man_die2.ogg
sound/rng/morass_beta/sounds/npc/de_man/de_man_die3.ogg
sound/rng/morass_beta/sounds/npc/de_man/de_man_pain.ogg
sound/rng/morass_beta/sounds/npc/de_man/de_man_pain2.ogg
sound/rng/morass_beta/sounds/npc/de_man/de_man_pain3.ogg
sound/rng/morass_beta/sounds/npc/morassbeast/beast_alert.ogg
sound/rng/morass_beta/sounds/npc/morassbeast/beast_attack.ogg
sound/rng/morass_beta/sounds/npc/morassbeast/beast_attack2.ogg
sound/rng/morass_beta/sounds/npc/morassbeast/beast_idle.ogg
sound/rng/morass_beta/sounds/npc/morassbeast/beast_idle2.ogg
sound/rng/morass_beta/sounds/npc/morassbeast/beast_idle3.ogg
sound/rng/morass_beta/sounds/npc/morassbeast/beast_idle4.ogg
sound/rng/morass_beta/sounds/npc/morassbeast/beast_pain.ogg
sound/rng/morass_beta/sounds/npc/morassbeast/beast_pain2.ogg
sound/rng/morass_beta/sounds/npc/morassbeast/beast_strike.ogg
sound/rng/morass_beta/sounds/npc/repeater/rep_attack.ogg
sound/rng/morass_beta/sounds/npc/repeater/rep_die.ogg
sound/rng/morass_beta/sounds/npc/repeater/rep_die2.ogg
sound/rng/morass_beta/sounds/npc/repeater/rep_pain1.ogg
sound/rng/morass_beta/sounds/npc/repeater/rep_pain2.ogg
sound/rng/morass_beta/sounds/npc/repeater/rep_shoot.ogg
sound/rng/morass_beta/sounds/npc/repeater/rep_speak.ogg
sound/rng/morass_beta/sounds/npc/repeater/rep_speak2.ogg
sound/rng/morass_beta/sounds/npc/repeater/rep_speak3.ogg
sound/rng/morass_beta/sounds/npc/rtrooper/rt_attack.ogg
sound/rng/morass_beta/sounds/npc/rtrooper/rt_die.ogg
sound/rng/morass_beta/sounds/npc/rtrooper/rt_die2.ogg
sound/rng/morass_beta/sounds/npc/rtrooper/rt_pain.ogg
sound/rng/morass_beta/sounds/npc/rtrooper/rt_pain2.ogg
sound/rng/morass_beta/sounds/npc/rtrooper/rt_shoot.ogg
sound/rng/morass_beta/sounds/npc/rtrooper/rt_speak.ogg
sound/rng/morass_beta/sounds/npc/rtrooper/rt_speak2.ogg
sound/rng/morass_beta/sounds/npc/rtrooper/rt_speak3.ogg
sound/rng/morass_beta/sounds/npc/worm/worm_alert.ogg
sound/rng/morass_beta/sounds/npc/worm/worm_attack.ogg
sound/rng/morass_beta/sounds/npc/worm/worm_speak.ogg
sound/rng/morass_beta/sounds/npc/worm/worm_speak2.ogg
sound/rng/morass_beta/sounds/npc/worm/worm_die.ogg
sound/rng/morass_beta/sounds/npc/worm/worm_pain.ogg
sound/rng/morass_beta/sounds/npc/worm/worm_pain2.ogg
sound/rng/morass_beta/sounds/npc/moreyelling/aaah.ogg
sound/rng/morass_beta/sounds/npc/moreyelling/aaah2.ogg
sound/rng/morass_beta/sounds/npc/moreyelling/aaah3.ogg
sound/rng/morass_beta/sounds/npc/moreyelling/oooh.ogg
sound/rng/morass_beta/sounds/npc/moreyelling/oooh2.ogg
sound/rng/morass_beta/sounds/npc/moreyelling/oooh3.ogg

models/player/morass_beak/morass_beak.mdl
models/player/morass_beak/morass_beak.bmp
models/player/morass_guy1/morass_guy1.mdl
models/player/morass_guy1/morass_guy1.bmp
models/player/morass_guy2/morass_guy2.mdl
models/player/morass_guy2/morass_guy2.bmp
models/player/morass_guy3/morass_guy3.mdl
models/player/morass_guy3/morass_guy3.bmp
models/player/morass_guy4/morass_guy4.mdl
models/player/morass_guy4/morass_guy4.bmp
models/player/morass_mad/morass_mad.mdl
models/player/morass_mad/morass_mad.bmp
models/player/morass_hood/morass_hood.mdl
models/player/morass_hood/morass_hood.bmp
models/player/morass_rat/morass_rat.mdl
models/player/morass_rat/morass_rat.bmp

models/rngstuff/deluge_beta/weapons_v3/v_pistol.mdl
models/rngstuff/deluge_beta/weapons/w_pistol.mdl
models/rngstuff/deluge_beta/weapons/p_pistol.mdl
models/rngstuff/deluge_beta/weapons_v3/v_carbine.mdl
models/rngstuff/deluge_beta/weapons/w_carbine.mdl
models/rngstuff/deluge_beta/weapons/p_carbine.mdl
models/rngstuff/deluge_beta/weapons_v3/v_smg.mdl
models/rngstuff/deluge_beta/weapons/w_smg.mdl
models/rngstuff/deluge_beta/weapons/p_smg.mdl
models/rngstuff/deluge_beta/weapons/v_steampipe.mdl
models/rngstuff/deluge_beta/weapons/w_steampipe.mdl
models/rngstuff/deluge_beta/weapons/p_steampipe.mdl
models/rngstuff/deluge_beta/weapons_v3/v_scattergun.mdl
models/rngstuff/deluge_beta/weapons/w_scattergun.mdl
models/rngstuff/deluge_beta/weapons/p_scattergun.mdl
models/rngstuff/deluge_beta/weapons_v3/v_magnum.mdl
models/rngstuff/deluge_beta/weapons/w_magnum.mdl
models/rngstuff/deluge_beta/weapons/p_magnum.mdl
models/rngstuff/deluge_beta/weapons_v3/v_machinegun.mdl
models/rngstuff/deluge_beta/weapons/w_machinegun.mdl
models/rngstuff/deluge_beta/weapons/p_machinegun.mdl
models/rngstuff/deluge_beta/weapons_v3/v_propulsion.mdl
models/rngstuff/deluge_beta/weapons/w_propulsion.mdl
models/rngstuff/deluge_beta/weapons/p_propulsion.mdl
models/rngstuff/deluge_beta/weapons_v3/v_rifle.mdl
models/rngstuff/deluge_beta/weapons/w_rifle.mdl
models/rngstuff/deluge_beta/weapons/p_rifle.mdl
models/rngstuff/deluge_beta/weapons/v_gundor.mdl
models/rngstuff/deluge_beta/weapons/w_gundor.mdl
models/rngstuff/deluge_beta/weapons/p_gundor.mdl
models/rngstuff/deluge_beta/weapons/v_fists.mdl
models/rngstuff/deluge_beta/weapons/p_fists.mdl

models/rngstuff/morass_beta/condor.mdl
models/rngstuff/morass_beta/de_armorman_v2.mdl
models/rngstuff/morass_beta/de_beakmask.mdl
models/rngstuff/morass_beta/de_bimbo.mdl
models/rngstuff/morass_beta/de_gasmask.mdl
models/rngstuff/morass_beta/de_grunt_v2.mdl
models/rngstuff/morass_beta/de_man_v2.mdl
models/rngstuff/morass_beta/de_worm.mdl
models/rngstuff/morass_beta/morassbeast.mdl
models/rngstuff/morass_beta/mutant_repeater.mdl
models/rngstuff/morass_beta/mutant_repeater01.mdl
models/rngstuff/morass_beta/rtrooper.mdl
models/rngstuff/morass_beta/rtrooper01.mdl
models/rngstuff/morass_beta/de_roach.mdl

models/rngstuff/morass_beta/item/invisible.mdl
models/rngstuff/morass_beta/item/w_ammo_battery.mdl
models/rngstuff/morass_beta/item/w_ammo_magnum.mdl
models/rngstuff/morass_beta/item/w_ammo_pistol.mdl
models/rngstuff/morass_beta/item/w_ammo_rifle.mdl
models/rngstuff/morass_beta/item/w_ammo_shotgun.mdl
models/rngstuff/morass_beta/item/w_ammo_smg.mdl
models/rngstuff/morass_beta/item/w_armor.mdl
models/rngstuff/morass_beta/item/w_medkit.mdl
models/rngstuff/morass_beta/item/w_morass_pickup.mdl
models/rngstuff/morass_beta/item/w_rotating_pickup_v3.mdl
models/rngstuff/morass_beta/item/w_powerup.mdl

models/rngstuff/morass_beta/prop/mo_stone1.mdl
models/rngstuff/morass_beta/prop/mo_stone2.mdl
models/rngstuff/morass_beta/prop/newcomputerbroken.mdl
models/rngstuff/morass_beta/prop/officechairbroken.mdl
models/rngstuff/morass_beta/prop/officeshelfbroken.mdl
models/rngstuff/morass_beta/prop/treecluster_shrubs.mdl
models/rngstuff/morass_beta/prop/smalltrees.mdl
models/rngstuff/morass_beta/prop/spinaltree.mdl
models/rngstuff/morass_beta/prop/fixed_treecluster.mdl
models/rngstuff/morass_beta/prop/fixed_zp_tree01.mdl
models/rngstuff/morass_beta/prop/DGF_condor_eye.mdl
models/rngstuff/morass_beta/prop/DGF_eye_gibs.mdl
models/rngstuff/morass_beta/prop/barrels.mdl

sprites/morass_beta/fire3mono.spr
sprites/morass_beta/mist1.spr
sprites/morass_beta/mo_portal.spr
sprites/morass_beta/pow_godmode.spr
sprites/morass_beta/pow_health.spr
sprites/morass_beta/pow_invis.spr
sprites/smokepuff.spr

gfx/env/morassbk.tga
gfx/env/morassdn.tga
gfx/env/morassft.tga
gfx/env/morasslf.tga
gfx/env/morassrt.tga
gfx/env/morassup.tga