maps/dis_beta.gmr
maps/dis_beta.gsr
maps/dis_beta_motd.txt
models/rngremake/invisible.mdl
models/rngremake/rmk_barney.mdl
models/rngremake/rmk_doc.mdl
models/rngremake/rmk_medic.mdl
models/rngremake/rmk_rng.mdl
models/rngremake/rmk_trooper.mdl
models/rngremake/rmk_trooper_apache.mdl
models/rngremake/rmk_trooper_mask.mdl
models/rngremake/rmk_trooper_osprey.mdl
models/rngremake/rmk_trooper_vulgar.mdl
models/rngremake/k_beast.mdl
models/rngremake/k_dead_trooper.mdl
models/rngremake/k_mutant_jackal.mdl
models/rngremake/k_slave.mdl
models/rngremake/k_slave_undead.mdl
models/rngremake/k_zombie.mdl
models/rngremake/deadbush.mdl
models/rngremake/deadtree.mdl
models/rngremake/dgf_portal_snow.mdl
models/rngremake/portal_uni.mdl
models/rngremake/dissection_mo.mdl
models/rngremake/eye.mdl
models/rngremake/remakeitem.mdl
models/rngremake/remakeitem2.mdl
models/rngremake/riverlamp.mdl
models/rngremake/torchpipe.mdl
models/rngremake/weapons/v_fists.mdl
models/rngremake/weapons/v_pistol18.mdl
models/rngremake/weapons/v_delugeshotgun.mdl
models/rngremake/weapons/v_smg_tom.mdl
models/rngremake/weapons/v_railgun.mdl
models/rngremake/weapons/w_pistol18.mdl
models/rngremake/weapons/w_delugeshotgun.mdl
models/rngremake/weapons/w_smg_tom.mdl
models/rngremake/weapons/w_railgun.mdl
models/rngremake/weapons/p_fists.mdl
models/rngremake/weapons/p_pistol18.mdl
models/rngremake/weapons/p_delugeshotgun.mdl
models/rngremake/weapons/p_smg_tom.mdl
models/rngremake/weapons/p_railgun.mdl
models/rngremake/weapons/w_ammo_pistol.mdl
models/rngremake/weapons/w_ammo_shotgun.mdl
models/rngremake/weapons/w_ammo_smg.mdl
models/rngremake/weapons/w_ammo_energy.mdl
models/rngremake/weapons/w_ammo_alien.mdl
models/rngremake/weapons/smg_grenade.mdl
models/player/dis_barney/dis_barney.mdl
models/player/dis_barney/dis_barney.bmp
models/player/dis_condor/dis_condor.mdl
models/player/dis_condor/dis_condor.bmp
models/player/dis_gman/dis_gman.mdl
models/player/dis_gman/dis_gman.bmp
models/player/dis_gordon/dis_gordon.mdl
models/player/dis_gordon/dis_gordon.bmp
models/player/dis_kate/dis_kate.mdl
models/player/dis_kate/dis_kate.bmp
models/player/dis_mad/dis_mad.mdl
models/player/dis_mad/dis_mad.bmp
models/player/dis_ratty/dis_ratty.mdl
models/player/dis_ratty/dis_ratty.bmp
sound/rngremake/area.ogg
sound/rngremake/secret.ogg
sound/rngremake/secret2.ogg
sound/rngremake/secret3.ogg
sound/rngremake/secretremake.ogg
sound/rngremake/music/dis_loop.ogg
sound/rngremake/music/gallery_loop.ogg
sound/rngremake/music/gallery2_loop.ogg
sound/rngremake/music/introscene.ogg
sound/rngremake/music/dis1_outro.ogg
sound/rngremake/music/hintscreen.ogg
sound/rngremake/music/mainframe.ogg
sound/rngremake/music/ragepart.ogg
sound/rngremake/music/redhallway.ogg
sound/rngremake/music/datarouter.ogg
sound/rngremake/music/monitors.ogg
sound/rngremake/music/redkeyambush.ogg
sound/rngremake/music/greenkeyambush.ogg
sound/rngremake/music/bluekeyambush.ogg
sound/rngremake/weapons/beamexplode.ogg
sound/rngremake/weapons/beamhit.ogg
sound/rngremake/weapons/fist_draw.ogg
sound/rngremake/weapons/fist_hitbody.ogg
sound/rngremake/weapons/fist_hitwall.ogg
sound/rngremake/weapons/fist_swing.ogg
sound/rngremake/weapons/fist_voice_kick.ogg
sound/rngremake/weapons/fist_voice_prepare.ogg
sound/rngremake/weapons/fist_voice.ogg
sound/rngremake/weapons/fist_voice2.ogg
sound/rngremake/weapons/fist_voice3.ogg
sound/rngremake/weapons/kick_hitbody.ogg
sound/rngremake/weapons/kick_hitwall.ogg
sound/rngremake/weapons/kick_swing.ogg
sound/rngremake/weapons/pistol_draw.ogg
sound/rngremake/weapons/pistol_empty.ogg
sound/rngremake/weapons/pistol_fire.ogg
sound/rngremake/weapons/pistol_fire_alt.ogg
sound/rngremake/weapons/railgun_alt_explode.ogg
sound/rngremake/weapons/railgun_draw.ogg
sound/rngremake/weapons/railgun_empty.ogg
sound/rngremake/weapons/railgun_fire.ogg
sound/rngremake/weapons/railgun_fire_alt.ogg
sound/rngremake/weapons/railgun_windup.ogg
sound/rngremake/weapons/shotgun_draw.ogg
sound/rngremake/weapons/shotgun_empty.ogg
sound/rngremake/weapons/shotgun_fire.ogg
sound/rngremake/weapons/shotgun_pump.ogg
sound/rngremake/weapons/smg_draw.ogg
sound/rngremake/weapons/smg_empty.ogg
sound/rngremake/weapons/smg_fire.ogg
sound/rngremake/weapons/smg_gren_bounce.ogg
sound/rngremake/weapons/smg_gren_explode.ogg
sound/rngremake/weapons/smg_gren_fire.ogg
sound/rngremake/ambience/alienhum_loop.ogg
sound/rngremake/ambience/compmoan_loop.ogg
sound/rngremake/ambience/comproom_loop.ogg
sound/rngremake/ambience/cycler_loop.ogg
sound/rngremake/ambience/encroom_loop.ogg
sound/rngremake/ambience/hallwayalarm_loop.ogg
sound/rngremake/ambience/hallwayhum_loop.ogg
sound/rngremake/ambience/hallwaymoan_loop.ogg
sound/rngremake/ambience/hangar_loop.ogg
sound/rngremake/ambience/oldgarden_loop.ogg
sound/rngremake/ambience/wrathroom_loop.ogg
sound/rngremake/doors/door_open.ogg
sound/rngremake/doors/door_close.ogg
sound/rngremake/doors/doorheavy_open.ogg
sound/rngremake/doors/doorheavy_close.ogg
sound/rngremake/doors/stonedoor_open.ogg
sound/rngremake/doors/stonedoor_close.ogg
sound/rngremake/doors/platform_open.ogg
sound/rngremake/doors/platform_close.ogg
sound/rngremake/doors/hatch_open.ogg
sound/rngremake/doors/hatch_close.ogg
sound/rngremake/doors/gate_open.ogg
sound/rngremake/doors/gate_close.ogg
sound/rngremake/doors/ancientplat_open.ogg
sound/rngremake/doors/ancientplat_close.ogg
sound/rngremake/doors/locked.ogg
sound/rngremake/doors/button1.ogg
sound/rngremake/doors/button2.ogg
sound/rngremake/doors/button_switch.ogg
sound/rngremake/events/rocket_alarm.ogg
sound/rngremake/events/rocket_breakwall1.ogg
sound/rngremake/events/rocket_breakwall2.ogg
sound/rngremake/events/rocket_breakwall3.ogg
sound/rngremake/events/rocket_count.ogg
sound/rngremake/events/rocket_ignite.ogg
sound/rngremake/items/ammo_alien.ogg
sound/rngremake/items/ammo_energy.ogg
sound/rngremake/items/ammo_pistol.ogg
sound/rngremake/items/ammo_shotgun.ogg
sound/rngremake/items/ammo_smg.ogg
sound/rngremake/items/item_respawn.ogg
sound/rngremake/items/itempick.ogg
sound/rngremake/items/itemuse.ogg
sound/rngremake/items/keyinsert.ogg
sound/rngremake/items/keypick.ogg
sound/rngremake/items/oem.ogg
sound/rngremake/items/oempick.ogg
sound/rngremake/items/pick_armor.ogg
sound/rngremake/items/pick_weapon.ogg
sound/rngremake/items/weapon.ogg
sound/rngremake/npc/trooper/troop_attack.ogg
sound/rngremake/npc/trooper/troop_death.ogg
sound/rngremake/npc/trooper/troop_death2.ogg
sound/rngremake/npc/trooper/troop_death3.ogg
sound/rngremake/npc/trooper/troop_idle.ogg
sound/rngremake/npc/trooper/troop_idle2.ogg
sound/rngremake/npc/trooper/troop_idle3.ogg
sound/rngremake/npc/trooper/troop_pain.ogg
sound/rngremake/npc/trooper/troop_pain2.ogg
sound/rngremake/npc/trooper/troop_speak.ogg
sound/rngremake/npc/trooper/troop_speak2.ogg
sound/rngremake/npc/trooper/troop_speak3.ogg
sound/rngremake/npc/trooper/troop_speak4.ogg
sound/rngremake/npc/trooper/troop_speak5.ogg
sound/rngremake/npc/trooper/troop_speak6.ogg
sprites/rngremake/beamglow.spr
sprites/rngremake/beampuff.spr
sprites/rngremake/beamspark.spr
sprites/rngremake/beamtrail.spr
sprites/rngremake/mist1.spr
sprites/rngremake/pipesteam1.spr
sprites/rngremake/pipesteam2.spr
sprites/rngremake/railgunbeam.spr
sprites/rngremake/weapon_pistol18.spr
sprites/rngremake/weapon_pistol18.txt
sprites/rngremake/weapon_delugeshotgun.spr
sprites/rngremake/weapon_assaultgun.txt
sprites/rngremake/weapon_smgtom.spr
sprites/rngremake/weapon_stensmg.txt
sprites/rngremake/weapon_railgun.spr
sprites/rngremake/weapon_railgun.txt
gfx/env/remakephobos_bk.tga
gfx/env/remakephobos_dn.tga
gfx/env/remakephobos_ft.tga
gfx/env/remakephobos_lf.tga
gfx/env/remakephobos_rt.tga
gfx/env/remakephobos_up.tga