// Created with resguy v7 (December 2017)
// https://github.com/wootguy/resguy

eshq.wad
gfx/env/eshq_pineve_bk.tga
gfx/env/eshq_pineve_dn.tga
gfx/env/eshq_pineve_ft.tga
gfx/env/eshq_pineve_lf.tga
gfx/env/eshq_pineve_rt.tga
gfx/env/eshq_pineve_up.tga
models/bath.mdl
models/bed2.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/hl/p_357.mdl
models/hl/v_357.mdl
models/hl/w_357.mdl
models/hl/w_357t.mdl
models/kitchensink.mdl
models/simplejeep.mdl
models/simplevan.mdl
models/toilet.mdl
models/tree1.mdl
models/tree2.mdl
models/tree3.mdl
sound/ambience/Accelerator1.wav
sound/ambience/clank1.wav
sound/ambience/generator2.wav
sound/ambience/generator4.wav
sound/ambience/ring1.wav
sound/ambience/ring2.wav
sound/ambience/teleport1.wav
sound/ambience/tunnelambient1.wav
sound/ambience/warn10.wav
sound/hl/weapons/357_reload1.wav
sound/hl/weapons/357_shot1.wav
sound/hl/weapons/357_shot2.wav
sound/vox/expected.wav
sprites/320hud1.spr
sprites/320hud2.spr
sprites/hl_weapons/weapon_hl357.txt
