// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/detail/rng/mokki_kivi2.tga
gfx/detail/rng/mokki_kivi4.tga
gfx/detail/rng/p_seina2.tga
gfx/detail/rng/p_seina4.tga
gfx/detail/rng/tehdas_metalli.tga
gfx/detail/rng/tehdas_metalli3.tga
gfx/detail/rng/tehdas_seina.tga
gfx/detail/rng/tehdas_seina2.tga
gfx/detail/rng/tehdas_seina3.tga
gfx/detail/rng/tehdas_seina5.tga
maps/mystic_radar_v1_detail.txt
models/mystic_radar/mr_bottle.mdl
models/mystic_radar/mr_zombcrab.mdl
models/mystic_radar/mr_zombie1.mdl
models/mystic_radar/mr_zombie1b.mdl
models/mystic_radar/mr_zombie2.mdl
models/mystic_radar/mr_zombie3.mdl
models/mystic_radar/p_rotcrowbar.mdl
models/mystic_radar/v_rotcrowbar.mdl
models/mystic_radar/w_rotcrowbar.mdl
sound/gonome/gonome_step1.wav
sound/mystic_radar/mr_ambient1a.mp3
sound/mystic_radar/mr_ambient1b.mp3
sound/mystic_radar/mr_ambient1c.mp3
sound/mystic_radar/mr_ambient2.mp3
sound/mystic_radar/mr_ambient2_i.mp3
sound/mystic_radar/mr_ambient3a.mp3
sound/mystic_radar/mr_door.wav
sound/mystic_radar/mr_item.wav
sound/mystic_radar/mr_keys.wav
sound/mystic_radar/mr_lamp.wav
sound/mystic_radar/mr_scream1.wav
sound/mystic_radar/mr_scream2.wav
sound/mystic_radar/mr_scream3.wav
sound/mystic_radar/mr_voice.wav
sound/mystic_radar/mr_zombie1/claw_miss1.wav
sound/mystic_radar/mr_zombie1/claw_miss2.wav
sound/mystic_radar/mr_zombie1/claw_strike1.wav
sound/mystic_radar/mr_zombie1/claw_strike2.wav
sound/mystic_radar/mr_zombie1/claw_strike3.wav
sound/mystic_radar/mr_zombie1/gonome_death2.wav
sound/mystic_radar/mr_zombie1/gonome_death3.wav
sound/mystic_radar/mr_zombie1/gonome_eat.wav
sound/mystic_radar/mr_zombie1/gonome_idle1.wav
sound/mystic_radar/mr_zombie1/gonome_idle2.wav
sound/mystic_radar/mr_zombie1/gonome_idle3.wav
sound/mystic_radar/mr_zombie1/gonome_melee1.wav
sound/mystic_radar/mr_zombie1/gonome_melee2.wav
sound/mystic_radar/mr_zombie1/gonome_pain1.wav
sound/mystic_radar/mr_zombie1/gonome_pain2.wav
sound/mystic_radar/mr_zombie1/gonome_pain3.wav
sound/mystic_radar/mr_zombie1/gonome_pain4.wav
sound/mystic_radar/mr_zombie1/hc_alert1.wav
sound/mystic_radar/mr_zombie1/hc_attack3.wav
sound/mystic_radar/mr_zombie1/hc_die1.wav
sound/mystic_radar/mr_zombie1/hc_die2.wav
sound/mystic_radar/mr_zombie1/hc_idle3.wav
sound/mystic_radar/mr_zombie1/hc_pain1.wav
sound/mystic_radar/mr_zombie1/hc_pain2.wav
sound/mystic_radar/mr_zombie1/hc_pain3.wav
sound/mystic_radar/mr_zombie1/zo_alert10.wav
sound/mystic_radar/mr_zombie1/zo_alert20.wav
sound/mystic_radar/mr_zombie1/zo_alert30.wav
sound/mystic_radar/mr_zombie1/zo_attack1.wav
sound/mystic_radar/mr_zombie1/zo_attack2.wav
sound/mystic_radar/mr_zombie1/zo_idle1.wav
sound/mystic_radar/mr_zombie1/zo_idle2.wav
sound/mystic_radar/mr_zombie1/zo_idle3.wav
sound/mystic_radar/mr_zombie1/zo_idle4.wav
sound/mystic_radar/mr_zombie1/zo_pain1.wav
sound/mystic_radar/mr_zombie1/zo_pain2.wav
sound/mystic_radar/mystic_radar.mp3
