blackops.wad
gfx/env/metro_nitebk.tga
gfx/env/metro_nitedn.tga
gfx/env/metro_niteft.tga
gfx/env/metro_nitelf.tga
gfx/env/metro_nitert.tga
gfx/env/metro_niteup.tga
models/blackops/crossbow_bolt.mdl
models/blackops/gman.mdl
models/blackops/grenade.mdl
models/blackops/hassassin.mdl
models/blackops/hassassint.mdl
models/blackops/p_357.mdl
models/blackops/p_9mmar.mdl
models/blackops/p_9mmhandgun.mdl
models/blackops/p_crossbow.mdl
models/blackops/p_crowbar.mdl
models/blackops/p_grenade.mdl
models/blackops/p_katana.mdl
models/blackops/p_m16.mdl
models/blackops/p_medkit.mdl
models/blackops/p_rpg.mdl
models/blackops/p_shotgun.mdl
models/blackops/rpgrocket.mdl
models/blackops/shell.mdl
models/blackops/shotgunshell.mdl
models/blackops/tool_box.mdl
models/blackops/v_357.mdl
models/blackops/v_9mmar.mdl
models/blackops/v_9mmhandgun_hl.mdl
models/blackops/v_crossbow.mdl
models/blackops/v_crowbar.mdl
models/blackops/v_grenade.mdl
models/blackops/v_katana.mdl
models/blackops/v_m16a2.mdl
models/blackops/v_medkit.mdl
models/blackops/v_rpg.mdl
models/blackops/v_shotgun.mdl
models/blackops/w_357.mdl
models/blackops/w_357ammo.mdl
models/blackops/w_357ammobox.mdl
models/blackops/w_9mmar.mdl
models/blackops/w_9mmarclip.mdl
models/blackops/w_9mmclip.mdl
models/blackops/w_9mmclipt.mdl
models/blackops/w_9mmhandgun.mdl
models/blackops/w_battery.mdl
models/blackops/w_crossbow.mdl
models/blackops/w_crossbow_clip.mdl
models/blackops/w_crowbar.mdl
models/blackops/w_grenade.mdl
models/blackops/w_katana.mdl
models/blackops/w_m16.mdl
models/blackops/w_medkit.mdl
models/blackops/w_medkitt.mdl
models/blackops/w_pipe_wrench.mdl
models/blackops/w_pmedkit.mdl
models/blackops/w_pmedkitt.mdl
models/blackops/w_rpg.mdl
models/blackops/w_rpgammo.mdl
models/blackops/w_rpgammot.mdl
models/blackops/w_shotbox.mdl
models/blackops/w_shotgun.mdl
models/blackops/w_suit.mdl
sound/blackops/ambience/burn_small.wav
sound/blackops/ambience/fluorescent.wav
sound/blackops/ambience/night2.wav
sound/blackops/mp3/hl28.wav
sound/weapons/629_shells_land.wav
sound/weapons/ayakashi_weapons/katana_attack1.wav
sound/weapons/ayakashi_weapons/katana_attack2.wav
sound/weapons/ayakashi_weapons/katana_charge.wav
sound/weapons/ayakashi_weapons/katana_chargeattack.wav
sound/weapons/ayakashi_weapons/katana_draw.wav
sound/weapons/g3_boltback.wav
sound/weapons/g3_boltforward.wav
sound/weapons/g3_magin.wav
sound/weapons/g3_magout.wav
sound/weapons/hks_clic1.wav
sound/weapons/m4a1_boltpull.wav
sound/weapons/m4a1_clipin.wav
sound/weapons/m4a1_clipout.wav
sound/weapons/m4a1_deploy.wav
sound/weapons/revolvers_bulletsin.wav
sound/weapons/revolvers_rod.wav
sound/weapons/revolvers_wheelin.wav
sound/weapons/revolvers_wheelout.wav
