maps/quad_f.res
maps/quad_f.cfg
maps/quad_f.gmr
maps/quad_f_motd.txt
maps/maiten_note.txt
sound/stream/music/epic1_loop.ogg
sound/stream/music/epic2_loop.ogg
sound/stream/music/epic3_loop.ogg
sound/stream/music/epic4_loop.ogg
sound/stream/sfx/alarm-clock-1.wav
sound/stream/sfx/clock-ticking-1.wav
sound/stream/sfx/portal_enter.wav
sound/stream/sfx/portal_exit.wav
sound/stream/sfx/portal_open.wav
sound/stream/sfx/portal_shoot.wav
models/quad_f/maiten/maiten_counter.mdl
models/quad_f/maiten/maiten_counter_players.mdl
models/quad_f/maiten/sig.mdl
models/quad_f/maiten/top.mdl