// Created with resguy v8 (September 2018)
// https://github.com/wootguy/resguy

models/REvil/Balathron.mdl
models/REvil/chicken.mdl
models/REvil/chickent.mdl
models/REvil/civilian1.mdl
models/REvil/civilian101.mdl
models/REvil/Furnature/xen_trailer.mdl
models/REvil/Furnature/xen_tree4_3.mdl
models/REvil/Furnature/xen_tree5_3.mdl
models/REvil/Furnature/xen_tree7_1.mdl
models/REvil/Furnature/xen_tree7_4.mdl
models/REvil/girl1.mdl
models/REvil/hgrunt.mdl
models/REvil/hunteralpha.mdl
models/REvil/IModels/w_crowbar.mdl
models/REvil/IModels/w_crowbart.mdl
models/REvil/IModels/w_isotopebox.mdl
models/REvil/IModels/w_isotopeboxt.mdl
models/REvil/IModels/w_kevlar.mdl
models/REvil/specialops.mdl
models/REvil/szombie.mdl
models/REvil/szombieT.mdl
models/REvil/WModels/357/v_357_v2.mdl
models/REvil/WModels/beretta/v_9mmhandgun.mdl
models/REvil/WModels/Chainsaw/p_chainsaw.mdl
models/REvil/WModels/Chainsaw/v_chainsaw.mdl
models/REvil/WModels/Chainsaw/w_chainsaw.mdl
models/REvil/WModels/Grenade/v_grenade_v2.mdl
models/REvil/WModels/M3/v_shotgun_v2.mdl
models/REvil/WModels/m4/p_9mmar.mdl
models/REvil/WModels/m4/v_9mmar.mdl
models/REvil/WModels/m40a1/v_m40a1.mdl
models/REvil/WModels/Medkit/v_medkit.mdl
models/REvil/WModels/tripmine/v_tripmine.mdl
sound/balathron/pl_step2-a5.wav
sound/balathron/pl_step3-a5.wav
sound/balathron/role7_die1.wav
sound/balathron/role7_idle1.wav
sound/balathron/role7_move1.wav
sound/balathron/role7_move2.wav
sound/balathron/role7_pain1.wav
sound/balathron/role7_spawn1.wav
sound/balathron/role7_wound1.wav
sound/REvil/Misfits - Day Of The Dead.wav
sound/REvil/Misfits - Hunting Humans.wav
sound/REzombie/claw_miss1.wav
sound/REzombie/claw_miss2.wav
sound/REzombie/claw_strike1.wav
sound/REzombie/claw_strike2.wav
sound/REzombie/claw_strike3.wav
sound/REzombie/zo_alert10.wav
sound/REzombie/zo_alert20.wav
sound/REzombie/zo_alert30.wav
sound/REzombie/zo_attack1.wav
sound/REzombie/zo_attack2.wav
sound/REzombie/zo_idle1.wav
sound/REzombie/zo_idle2.wav
sound/REzombie/zo_idle3.wav
sound/REzombie/zo_idle4.wav
sound/REzombie/zo_pain1.wav
sound/REzombie/zo_pain2.wav
