// Created with resguy v6 (November 2017)
// https://github.com/wootguy/resguy

gfx/env/londonbk.tga
gfx/env/londondn.tga
gfx/env/londonft.tga
gfx/env/londonlf.tga
gfx/env/londonrt.tga
gfx/env/londonup.tga
models/raccoon/Chris.mdl
models/raccoon/Police_Car_e4g1e.mdl
models/raccoon/RPD_statue.mdl
models/raccoon/Smashed_PoliceCar.mdl
models/raccoon/WModels/357/v_357.mdl
models/raccoon/WModels/BravoMP5/p_9mmAR.mdl
models/raccoon/WModels/BravoMP5/v_9mmAR.mdl
models/raccoon/WModels/BravoMP5/w_9mmAR.mdl
models/raccoon/WModels/Knife/p_crowbar.mdl
models/raccoon/WModels/Knife/v_crowbar.mdl
models/raccoon/WModels/Knife/w_crowbar.mdl
models/raccoon/WModels/Pump/p_shotgun.mdl
models/raccoon/WModels/Pump/v_shotgun.mdl
models/raccoon/WModels/Pump/w_shotgun.mdl
models/raccoon/WModels/Socom/p_9mmhandgun.mdl
models/raccoon/WModels/Socom/v_9mmhandgun.mdl
models/raccoon/WModels/Socom/w_9mmhandgun.mdl
models/raccoon/baricade.mdl
models/raccoon/barney.mdl
models/raccoon/barney01.mdl
models/raccoon/barney02.mdl
models/raccoon/barney03.mdl
models/raccoon/barneyt.mdl
models/raccoon/bench3.mdl
models/raccoon/cashregister.mdl
models/raccoon/cerberus.mdl
models/raccoon/cone_bloody.mdl
models/raccoon/corpse_male1.mdl
models/raccoon/e4g1e_corolla.mdl
models/raccoon/e4g1e_lada5.mdl
models/raccoon/geo_tire.mdl
models/raccoon/gonome.mdl
models/raccoon/green_herb.mdl
models/raccoon/hunter.mdl
models/raccoon/hydrant.mdl
models/raccoon/key.mdl
models/raccoon/key_rusty.mdl
models/raccoon/keyT.mdl
models/raccoon/lamp4-1.mdl
models/raccoon/lamp4-2.mdl
models/raccoon/lamp_hanging-industrial-no_lamp.mdl
models/raccoon/nemesis.mdl
models/raccoon/pipe_bubbles.mdl
models/raccoon/racam.mdl
models/raccoon/rubbishbin.mdl
models/raccoon/smashed_swatvan.mdl
models/raccoon/toilet.mdl
models/raccoon/trash1.mdl
models/raccoon/truck_old.mdl
models/raccoon/umbrella1.mdl
models/raccoon/umbrellaflag.mdl
models/raccoon/van.mdl
models/raccoon/vat_charlie.mdl
models/raccoon/vendetta_streetlamp.mdl
models/raccoon/vendetta_streetlamp_shade.mdl
models/raccoon/warehouse_shelf001.mdl
models/raccoon/wheelchair_sci.mdl
models/raccoon/wheelchair_sci01.mdl
models/raccoon/wheelchair_sci02.mdl
models/raccoon/xt_lamp.mdl
models/raccoon/zombie.mdl
models/raccoon/zombie01.mdl
models/raccoon/zombie02.mdl
models/raccoon/zombie03.mdl
models/raccoon/zombieT.mdl
racoon.wad
sound/raccoon/access.wav
sound/raccoon/ap_rotor4.wav
sound/raccoon/burnin.wav
sound/raccoon/chamb.wav
sound/raccoon/cityambience.wav
sound/raccoon/clockstrike.wav
sound/raccoon/computerstart.wav
sound/raccoon/defense2.wav
sound/raccoon/der.wav
sound/raccoon/dooropen.wav
sound/raccoon/doorunlock.wav
sound/raccoon/endtheme.wav
sound/raccoon/fountain.wav
sound/raccoon/foxtheme.wav
sound/raccoon/hall2.wav
sound/raccoon/house.wav
sound/raccoon/idlecomputer.wav
sound/raccoon/inalarm.wav
sound/raccoon/keyfall.wav
sound/raccoon/lib.wav
sound/raccoon/lorrycrashy.wav
sound/raccoon/machine.wav
sound/raccoon/moonlight.wav
sound/raccoon/motor.wav
sound/raccoon/prelude.wav
sound/raccoon/queendie.wav
sound/raccoon/re3firstfloor.wav
sound/raccoon/reambience.wav
sound/raccoon/retitle2.wav
sound/raccoon/ruin.wav
sound/raccoon/safe.wav
sound/raccoon/screamman.wav
sound/raccoon/signalgear1.wav
sound/raccoon/siren.wav
sound/raccoon/squeaky.wav
sound/raccoon/stars.wav
sound/raccoon/static.wav
sound/raccoon/strike.wav
sound/raccoon/suicide.wav
sound/raccoon/thering.wav
sound/raccoon/thrill.wav
sound/raccoon/traitor.wav
sound/raccoon/trap.wav
sound/raccoon/voice2.wav
sound/raccoon/winstartup.wav
sprites/raccoon/fire1.spr
sprites/raccoon/item_glint.spr
sprites/raccoon/smoker.spr
