// .res file by R4to0.exe downloaded from HLDM-BR.NET
// Items commented out are included for reference only ...
// The server will precache/force download at commented files on its own so don't enable them!
// This will conserve some bandwidth avoiding downloading same file twice!
// Thanks, R4to0.

howtoinstall.txt
maps/RECO.res
//maps/RECO.CFG
//maps/RECO_skl.cfg
models/Player/RE_DEAD_Brad/RE_DEAD_Brad.mdl
models/Player/RE_HCF_Wesker/RE_HCF_Wesker.mdl
models/Player/RE_Outbreak_David/RE_Outbreak_David.mdl
models/Player/RE_RPD_Leon/RE_RPD_Leon.mdl
models/Player/RE_STARS_Barry/RE_STARS_Barry.mdl
models/Player/RE_STARS_Brad/RE_STARS_Brad.mdl
models/Player/RE_STARS_Chris/RE_STARS_Chris.mdl
models/Player/RE_STARS_Enrico/RE_STARS_Enrico.mdl
models/Player/RE_STARS_Forrest/RE_STARS_Forrest.mdl
models/Player/RE_STARS_Jill/RE_STARS_Jill.mdl
models/Player/RE_STARS_Joseph/RE_STARS_Joseph.mdl
models/Player/RE_STARS_Kenneth/RE_STARS_Kenneth.mdl
models/Player/RE_STARS_Rebecca/RE_STARS_Rebecca.mdl
models/Player/RE_STARS_Richard/RE_STARS_Richard.mdl
models/Player/RE_STARS_Wesker/RE_STARS_Wesker.mdl
models/Player/RE_UBCS_Asian/RE_UBCS_Asian.mdl
models/Player/RE_UBCS_Black/RE_UBCS_Black.mdl
models/Player/RE_UBCS_Hispanic/RE_UBCS_Hispanic.mdl
models/Player/RE_UBCS_Mikhail/RE_UBCS_Mikhail.mdl
models/Player/RE_UBCS_Militia/RE_UBCS_Militia.mdl
models/Player/RE_UBCS_Nicholai/RE_UBCS_Nicholai.mdl
models/Player/RE_UBCS_White/RE_UBCS_White.mdl
models/Player/RE_UMBRELLA_Alfred/RE_UMBRELLA_Alfred.mdl
models/Player/RE_UMBRELLA_Hunk/RE_UMBRELLA_Hunk.mdl
models/Player/RE_UMBRELLA_MrX/RE_UMBRELLA_MrX.mdl
models/Player/RE_UMBRELLA_Nemesis/RE_UMBRELLA_Nemesis.mdl
//models/reco/Archvile.mdl
//models/reco/biggator.mdl
models/reco/crawlerT.mdl
//models/reco/crimson.mdl
//models/reco/dead2.mdl
//models/reco/Furnature/butch_dead.mdl
//models/reco/Furnature/vat_charlie.mdl
//models/reco/girl1.mdl
//models/reco/gonome.mdl
//models/reco/gorger.mdl
models/reco/gorgerT.mdl
//models/reco/hunter.mdl
models/reco/hunteralpha.mdl
models/reco/IModels/357ammo.mdl
models/reco/IModels/357ammot.mdl
//models/reco/IModels/Adrenaline.mdl
models/reco/IModels/AdrenalineT.mdl
//models/reco/IModels/allied_ammo.mdl
//models/reco/IModels/brownshield.mdl
models/reco/IModels/forkey.mdl
//models/reco/IModels/goldshield.mdl
//models/reco/IModels/resource_cd.mdl
models/reco/IModels/resource_datastreamer.mdl
models/reco/IModels/Resourse_CD.mdl
//models/reco/IModels/ring.mdl
//models/reco/IModels/shotshell.mdl
models/reco/IModels/shotshellt.mdl
//models/reco/IModels/spiggot.mdl
//models/reco/IModels/toolbox.mdl
//models/reco/IModels/w_357ammo.mdl
models/reco/IModels/w_357ammot.mdl
models/reco/IModels/w_crowbart.mdl
//models/reco/IModels/w_flare.mdl
models/reco/IModels/w_flaret.mdl
//models/reco/IModels/w_isotopebox.mdl
models/reco/IModels/w_IsotopeBoxT.mdl
//models/reco/IModels/w_kevlar.mdl
//models/reco/IModels/w_security.mdl
//models/reco/IModels/xen_folder2.mdl
//models/reco/licker.mdl
//models/reco/neptune.mdl
models/reco/neptuneT.mdl
//models/reco/reaver.mdl
//models/reco/sci.mdl
//models/reco/security.mdl
//models/reco/specialops.mdl
//models/reco/statue1.mdl
//models/reco/superlicker.mdl
models/reco/uspecialops.mdl
//models/reco/WModels/357/v_357.mdl
//models/reco/WModels/beretta/v_9mmhandgun.mdl
//models/reco/WModels/Chainsaw/p_chainsaw.mdl
//models/reco/WModels/Chainsaw/v_chainsaw.mdl
//models/reco/WModels/Chainsaw/w_chainsaw.mdl
//models/reco/WModels/GrapGun/p_grap.mdl
//models/reco/WModels/GrapGun/v_grap.mdl
//models/reco/WModels/GrapGun/w_grap.mdl
//models/reco/WModels/Knife/p_crowbar.mdl
//models/reco/WModels/Knife/v_crowbar.mdl
//models/reco/WModels/Knife/w_crowbar.mdl
//models/reco/WModels/M3/p_shotgun.mdl
//models/reco/WModels/M3/v_shotgun.mdl
//models/reco/WModels/M3/w_shotgun.mdl
models/reco/WModels/m4/p_9mmar.mdl
models/reco/WModels/m4/v_9mmar.mdl
models/reco/WModels/m4/w_9mmar.mdl
//models/reco/WModels/m40a1/v_m40a1.mdl
//models/reco/WModels/Medkit/v_medkit.mdl
//models/reco/WModels/Minigun/v_minigun.mdl
//models/reco/WModels/Scout/p_crossbow.mdl
//models/reco/WModels/Scout/v_crossbow.mdl
models/reco/WModels/Scout/v_scout.mdl
//models/reco/WModels/Scout/w_crossbow.mdl
//models/reco/WModels/USP9mmauto/p_uzi.mdl
//models/reco/WModels/USP9mmauto/v_uzi.mdl
models/reco/WModels/USP9mmauto/w_2uzis.mdl
models/reco/WModels/USP9mmauto/w_2uzis_gold.mdl
//models/reco/WModels/USP9mmauto/w_uzi.mdl
models/reco/WModels/USP9mmauto/w_uzi_gold.mdl
//models/reco/xscientist.mdl
//models/reco/zombie.mdl
sound/balathron/devour.wav
sound/balathron/devourcancel.wav
sound/balathron/devourcomplete.wav
sound/balathron/devourswallow.wav
sound/balathron/pl_step2-a5.wav
sound/balathron/pl_step3-a5.wav
sound/balathron/role7_die1.wav
sound/balathron/role7_idle1.wav
sound/balathron/role7_move1.wav
sound/balathron/role7_move2.wav
sound/balathron/role7_pain1.wav
sound/balathron/role7_spawn1.wav
sound/balathron/role7_wound1.wav
sound/RECO/Tyrant.txt
sound/RECO/zombie.txt
sound/revil/Bossbattle2.wav
sound/revil/cricket.wav
sound/revil/escapealarm.wav
sound/revil/heartbeat.wav
sound/revil/icky.wav
sound/revil/lookout!.wav
sound/revil/morph.wav
sound/revil/newscream2.wav
sound/revil/re2music1.wav
sound/revil/residentevil.wav
sound/revil/rjigalo.wav
sound/revil/scaryass.wav
sound/revil/SUPPLIEZ!.wav
sound/revil/tyrantburst1.wav
sound/revil/UmbrellaLab.wav
sound/revil/voxescapemessage.wav
"sound/revil/ZOMBIE ATTACK!.wav"
sound/revil/ZombieBurst2.wav
sound/REzombie/claw_miss1.wav
sound/REzombie/claw_miss2.wav
sound/REzombie/claw_strike1.wav
sound/REzombie/claw_strike2.wav
sound/REzombie/claw_strike3.wav
sound/REzombie/zo_alert10.wav
sound/REzombie/zo_alert20.wav
sound/REzombie/zo_alert30.wav
sound/REzombie/zo_attack1.wav
sound/REzombie/zo_attack2.wav
sound/REzombie/zo_idle1.wav
sound/REzombie/zo_idle2.wav
sound/REzombie/zo_idle3.wav
sound/REzombie/zo_idle4.wav
sound/REzombie/zo_pain1.wav
sound/REzombie/zo_pain2.wav
sound/REzombie/zo_pain3.wav
sound/Tyrant/null.wav
sound/Tyrant/primalscreaming.wav
sound/Tyrant/role4_idle1.wav
sound/Tyrant/role4_idle2.wav
sound/Tyrant/role4_idle3.wav
sound/Tyrant/role7_die2.wav
sound/Tyrant/role7_die3.wav
sound/Tyrant/role7_die4.wav
sound/Tyrant/role7_pain1.wav
sound/Tyrant/role7_spawn1.wav
sound/Tyrant/role7_wound1.wav
sound/Tyrant/role7_wound2.wav
sound/Tyrant/role7_wound3.wav
sound/Tyrant/role7_wound4.wav
sound/Tyrant/_period.wav
