gfx/env/hiruyamabk.tga
gfx/env/hiruyamadn.tga
gfx/env/hiruyamaft.tga
gfx/env/hiruyamalf.tga
gfx/env/hiruyamart.tga
gfx/env/hiruyamaup.tga
maps/ressya_no_tabi.bsp
maps/ressya_no_tabi.cfg
maps/ressya_no_tabi_motd.txt
models/ressya_no_tabi/baseball.mdl
models/ressya_no_tabi/big_ichy.mdl
models/ressya_no_tabi/big_ichyT.mdl
models/ressya_no_tabi/dango.mdl
models/ressya_no_tabi/dorobo_massn.mdl
models/ressya_no_tabi/katsusand.mdl
models/ressya_no_tabi/matsu.mdl
models/ressya_no_tabi/models.txt
models/ressya_no_tabi/p_baseball.mdl
models/ressya_no_tabi/p_bokutou.mdl
models/ressya_no_tabi/p_cupzake_c.mdl
models/ressya_no_tabi/p_cupzake_o.mdl
models/ressya_no_tabi/p_dice.mdl
models/ressya_no_tabi/p_medkit.mdl
models/ressya_no_tabi/p_shuriken.mdl
models/ressya_no_tabi/p_smartphone.mdl
models/ressya_no_tabi/proj_dice.mdl
models/ressya_no_tabi/shuriken.mdl
models/ressya_no_tabi/small_ichy.mdl
models/ressya_no_tabi/small_ichyT.mdl
models/ressya_no_tabi/superdry.mdl
models/ressya_no_tabi/takoyaki.mdl
models/ressya_no_tabi/udon.mdl
models/ressya_no_tabi/v_baseball.mdl
models/ressya_no_tabi/v_bokutou.mdl
models/ressya_no_tabi/v_cupzake.mdl
models/ressya_no_tabi/v_dice.mdl
models/ressya_no_tabi/v_medkit.mdl
models/ressya_no_tabi/v_shuriken.mdl
models/ressya_no_tabi/v_smartphone.mdl
models/ressya_no_tabi/w_baseball.mdl
models/ressya_no_tabi/w_bokutou.mdl
models/ressya_no_tabi/w_cupzake.mdl
models/ressya_no_tabi/w_dice1.mdl
models/ressya_no_tabi/w_dice2.mdl
models/ressya_no_tabi/w_dice3.mdl
models/ressya_no_tabi/w_dice4.mdl
models/ressya_no_tabi/w_dice5.mdl
models/ressya_no_tabi/w_dice6.mdl
models/ressya_no_tabi/w_pmedkit.mdl
models/ressya_no_tabi/w_shuriken.mdl
models/ressya_no_tabi/w_smartphone.mdl
models/ressya_no_tabi/youkan.mdl
sound/ressya_no_tabi/latin1s.mp3
sound/ressya_no_tabi/puu3.wav
sound/ressya_no_tabi/teikyou.wav
sound/ressya_no_tabi/tsurigane.wav
sound/takedeppo/50cal_fire.wav
sound/takedeppo/50cal_fun_time.wav
sprites/ressya_no_tabi/ammoicon.spr
sprites/ressya_no_tabi/ammoicon2.spr
sprites/ressya_no_tabi/badplus1.spr
sprites/ressya_no_tabi/camera.spr
sprites/ressya_no_tabi/fukidashi.spr
sprites/ressya_no_tabi/fukidashi_inf.spr
sprites/ressya_no_tabi/goodplus1.spr
sprites/ressya_no_tabi/owari.spr
sprites/ressya_no_tabi/teikyou.spr
sprites/ressya_no_tabi/title.spr
sprites/ressya_no_tabi/weapon_baseball.txt
sprites/ressya_no_tabi/weapon_bokutou.txt
sprites/ressya_no_tabi/weapon_cupzake.txt
sprites/ressya_no_tabi/weapon_dice.txt
sprites/ressya_no_tabi/weapon_shuriken.txt
sprites/ressya_no_tabi/weapon_smartphone.txt
sprites/ressya_no_tabi/weapon1.spr
sprites/ressya_no_tabi/weapon2.spr
sprites/ressya_no_tabi/weapon3.spr
sprites/ressya_no_tabi/yajirushi.spr
