// Created with resguy v4
// https://github.com/wootguy/resguy

maps/residual_life.gmr
maps/residual_life.gsr
maps/rl00r.res
models/player/cl_scientist1/cl_scientist1.mdl
models/player/cl_scientist2/cl_scientist2.mdl
models/player/cl_scientist3/cl_scientist3.mdl
models/player/cl_scientist4/cl_scientist4.mdl
models/player/cl_scientist5/cl_scientist5.mdl
models/player/cl_scientist6/cl_scientist6.mdl
models/residuallife/deadbarney.mdl
models/residuallife/otis.mdl
models/residuallife/weapons/p_chub.mdl
models/residuallife/weapons/v_357.mdl
models/residuallife/weapons/v_9mmar.mdl
models/residuallife/weapons/v_9mmhandgun.mdl
models/residuallife/weapons/v_chub.mdl
models/residuallife/weapons/v_crossbow.mdl
models/residuallife/weapons/v_crowbar.mdl
models/residuallife/weapons/v_desert_eagle.mdl
models/residuallife/weapons/v_displacer.mdl
models/residuallife/weapons/v_egon.mdl
models/residuallife/weapons/v_gauss.mdl
models/residuallife/weapons/v_grenade.mdl
models/residuallife/weapons/v_m16a2.mdl
models/residuallife/weapons/v_m40a1.mdl
models/residuallife/weapons/v_medkit.mdl
models/residuallife/weapons/v_pipe_wrench.mdl
models/residuallife/weapons/v_rpg.mdl
models/residuallife/weapons/v_satchel.mdl
models/residuallife/weapons/v_satchel_radio.mdl
models/residuallife/weapons/v_saw.mdl
models/residuallife/weapons/v_shotgun.mdl
models/residuallife/weapons/v_spore_launcher.mdl
models/residuallife/weapons/v_tripmine.mdl
models/residuallife/weapons/v_uzi.mdl
models/residuallife/weapons/w_chub.mdl
rl.wad
sound/residuallife/Kate.txt
sound/residuallife/music/ppharphir_nohim.wav
sound/residuallife/residual_sentences.txt
sound/residuallife/sentences/barney/s02ba_pl_door.wav
sound/residuallife/sentences/barney/sk02_ba_headdown.wav
sound/residuallife/sentences/otis/answer01.wav
sound/residuallife/sentences/otis/answer03.wav
sound/residuallife/sentences/otis/answer09.wav
sound/residuallife/sentences/otis/answer13.wav
sound/residuallife/sentences/otis/answer14.wav
sound/residuallife/sentences/otis/answer15.wav
sound/residuallife/sentences/otis/answer17.wav
sound/residuallife/sentences/otis/answer18.wav
sound/residuallife/sentences/otis/answer20.wav
sound/residuallife/sentences/otis/answer22.wav
sound/residuallife/sentences/otis/answer24.wav
sound/residuallife/sentences/otis/answer28.wav
sound/residuallife/sentences/otis/answer29.wav
sound/residuallife/sentences/otis/answer30.wav
sound/residuallife/sentences/otis/answer32.wav
sound/residuallife/sentences/otis/answer33.wav
sound/residuallife/sentences/otis/answer38.wav
sound/residuallife/sentences/otis/answer39.wav
sound/residuallife/sentences/otis/cit_hit01.wav
sound/residuallife/sentences/otis/cit_hit03.wav
sound/residuallife/sentences/otis/cit_hit04.wav
sound/residuallife/sentences/otis/cit_hit05.wav
sound/residuallife/sentences/otis/excuseme01.wav
sound/residuallife/sentences/otis/excuseme02.wav
sound/residuallife/sentences/otis/fantastic01.wav
sound/residuallife/sentences/otis/fantastic02.wav
sound/residuallife/sentences/otis/gordead_ans04.wav
sound/residuallife/sentences/otis/gordead_ques16.wav
sound/residuallife/sentences/otis/gotone01.wav
sound/residuallife/sentences/otis/gotone02.wav
sound/residuallife/sentences/otis/headsup01.wav
sound/residuallife/sentences/otis/headsup02.wav
sound/residuallife/sentences/otis/hi01.wav
sound/residuallife/sentences/otis/hi02.wav
sound/residuallife/sentences/otis/holddownspot01.wav
sound/residuallife/sentences/otis/holddownspot02.wav
sound/residuallife/sentences/otis/illstayhere01.wav
sound/residuallife/sentences/otis/imhurt01.wav
sound/residuallife/sentences/otis/imhurt02.wav
sound/residuallife/sentences/otis/imstickinghere01.wav
sound/residuallife/sentences/otis/incoming02.wav
sound/residuallife/sentences/otis/leadtheway01.wav
sound/residuallife/sentences/otis/letsgo01.wav
sound/residuallife/sentences/otis/letsgo02.wav
sound/residuallife/sentences/otis/likethat.wav
sound/residuallife/sentences/otis/littlecorner01.wav
sound/residuallife/sentences/otis/nice01.wav
sound/residuallife/sentences/otis/notthemanithought01.wav
sound/residuallife/sentences/otis/notthemanithought02.wav
sound/residuallife/sentences/otis/ohno.wav
sound/residuallife/sentences/otis/ok01.wav
sound/residuallife/sentences/otis/okimready01.wav
sound/residuallife/sentences/otis/okimready02.wav
sound/residuallife/sentences/otis/okimready03.wav
sound/residuallife/sentences/otis/ow01.wav
sound/residuallife/sentences/otis/ow02.wav
sound/residuallife/sentences/otis/pain03.wav
sound/residuallife/sentences/otis/pain05.wav
sound/residuallife/sentences/otis/pain06.wav
sound/residuallife/sentences/otis/pain07.wav
sound/residuallife/sentences/otis/pain08.wav
sound/residuallife/sentences/otis/pain09.wav
sound/residuallife/sentences/otis/pardonme01.wav
sound/residuallife/sentences/otis/question03.wav
sound/residuallife/sentences/otis/question05.wav
sound/residuallife/sentences/otis/question06.wav
sound/residuallife/sentences/otis/question07.wav
sound/residuallife/sentences/otis/question09.wav
sound/residuallife/sentences/otis/question11.wav
sound/residuallife/sentences/otis/question12.wav
sound/residuallife/sentences/otis/question17.wav
sound/residuallife/sentences/otis/question18.wav
sound/residuallife/sentences/otis/question20.wav
sound/residuallife/sentences/otis/question22.wav
sound/residuallife/sentences/otis/question25.wav
sound/residuallife/sentences/otis/question28.wav
sound/residuallife/sentences/otis/question29.wav
sound/residuallife/sentences/otis/readywhenyouare01.wav
sound/residuallife/sentences/otis/sorry01.wav
sound/residuallife/sentences/otis/sorry03.wav
sound/residuallife/sentences/otis/sorrydoc02.wav
sound/residuallife/sentences/otis/startle01.wav
sound/residuallife/sentences/otis/vanswer08.wav
sound/residuallife/sentences/otis/vanswer13.wav
sound/residuallife/sentences/otis/vquestion01.wav
sound/residuallife/sentences/otis/watchwhat.wav
sound/residuallife/sentences/otis/wetrustedyou01.wav
sound/residuallife/sentences/otis/yeah02.wav
sound/residuallife/sentences/otis/yougotit02.wav
sound/residuallife/weapons/chubby/toad_deploy1.wav
sound/residuallife/weapons/chubby/toad_die1.wav
sound/residuallife/weapons/chubby/toad_hunt1.wav
sound/residuallife/weapons/chubby/toad_hunt2.wav
