// Created with resguy v4
// https://github.com/wootguy/resguy

maps/residual_life.gmr
maps/residual_life.gsr
maps/rl02p.res
models/player/cl_scientist1/cl_scientist1.mdl
models/player/cl_scientist2/cl_scientist2.mdl
models/player/cl_scientist3/cl_scientist3.mdl
models/player/cl_scientist4/cl_scientist4.mdl
models/player/cl_scientist5/cl_scientist5.mdl
models/player/cl_scientist6/cl_scientist6.mdl
models/residuallife/civ_scientist.mdl
models/residuallife/cleansuit_scientist.mdl
models/residuallife/deadbarney.mdl
models/residuallife/food_tray.mdl
models/residuallife/otis.mdl
models/residuallife/weapons/p_chub.mdl
models/residuallife/weapons/v_357.mdl
models/residuallife/weapons/v_9mmar.mdl
models/residuallife/weapons/v_9mmhandgun.mdl
models/residuallife/weapons/v_chub.mdl
models/residuallife/weapons/v_crossbow.mdl
models/residuallife/weapons/v_crowbar.mdl
models/residuallife/weapons/v_desert_eagle.mdl
models/residuallife/weapons/v_displacer.mdl
models/residuallife/weapons/v_egon.mdl
models/residuallife/weapons/v_gauss.mdl
models/residuallife/weapons/v_grenade.mdl
models/residuallife/weapons/v_m16a2.mdl
models/residuallife/weapons/v_m40a1.mdl
models/residuallife/weapons/v_medkit.mdl
models/residuallife/weapons/v_pipe_wrench.mdl
models/residuallife/weapons/v_rpg.mdl
models/residuallife/weapons/v_satchel.mdl
models/residuallife/weapons/v_satchel_radio.mdl
models/residuallife/weapons/v_saw.mdl
models/residuallife/weapons/v_shotgun.mdl
models/residuallife/weapons/v_spore_launcher.mdl
models/residuallife/weapons/v_tripmine.mdl
models/residuallife/weapons/v_uzi.mdl
models/residuallife/weapons/w_chub.mdl
rl.wad
sound/residuallife/Kate.txt
sound/residuallife/residual_sentences.txt
sound/residuallife/sentences/otis/ow01.wav
sound/residuallife/sentences/otis/ow02.wav
sound/residuallife/sentences/otis/pain03.wav
sound/residuallife/sentences/otis/pain06.wav
sound/residuallife/sentences/otis/pain08.wav
sound/residuallife/sentences/otis/pain09.wav
sound/residuallife/sentences/fgrunt/ok03b_fg01.wav
sound/residuallife/sentences/ngrunt/ng_idle0.wav
sound/residuallife/sentences/ngrunt/ng_idle1.wav
sound/residuallife/sentences/ngrunt/ng_idle2.wav
sound/residuallife/sentences/ngrunt/ng_idle3.wav
sound/residuallife/weapons/chubby/toad_deploy1.wav
sound/residuallife/weapons/chubby/toad_die1.wav
sound/residuallife/weapons/chubby/toad_hunt1.wav
sound/residuallife/weapons/chubby/toad_hunt2.wav
