// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/detail/dt_snow1.tga
gfx/detail/rust/boot_grass_06.tga
gfx/detail/rust/I2SNOW2.tga
gfx/detail/rust/out_snd2.tga
gfx/detail/rust/out_snd3.tga
gfx/detail/rust/PRXOUTSAND4A.tga
loz.wad
maps/rust_mini_b9_detail.txt
maps/rust_mini_b9_materials.txt
models/afrikakorps/misc/gascan.mdl
models/cryoffear/syringe/p_syringe.mdl
models/cryoffear/syringe/v_syringe.mdl
models/cryoffear/syringe/w_syringe.mdl
models/rust/apache.mdl
models/rust/arc_bush.mdl
models/rust/arrow.mdl
models/rust/b17.mdl
models/rust/bush.mdl
models/rust/p_blueprint.mdl
models/rust/p_bow.mdl
models/rust/p_c4.mdl
models/rust/p_guitar.mdl
models/rust/p_hammer.mdl
models/rust/p_metal_hatchet.mdl
models/rust/p_metal_pickaxe.mdl
models/rust/p_rock.mdl
models/rust/p_stone_hatchet.mdl
models/rust/p_stone_pickaxe.mdl
models/rust/parachute.mdl
models/rust/pine_tree.mdl
models/rust/rock.mdl
models/rust/tr_barrel.mdl
models/rust/v_blueprint.mdl
models/rust/v_bow.mdl
models/rust/v_c4.mdl
models/rust/v_guitar.mdl
models/rust/v_hammer.mdl
models/rust/v_metal_hatchet.mdl
models/rust/v_metal_pickaxe.mdl
models/rust/v_rock.mdl
models/rust/v_stone_hatchet.mdl
models/rust/v_stone_pickaxe.mdl
models/rust/w_blueprint.mdl
models/rust/w_bow.mdl
models/rust/w_c4.mdl
models/rust/w_guitar.mdl
models/rust/w_hammer.mdl
models/rust/w_metal_hatchet.mdl
models/rust/w_metal_pickaxe.mdl
models/rust/w_rock.mdl
models/rust/w_stone_hatchet.mdl
models/rust/w_stone_pickaxe.mdl
rust_b6.wad
sound/cryoffear/weapons/syringe/syringe_inject.ogg
sound/cryoffear/weapons/syringe/syringe_insert.ogg
sound/cryoffear/weapons/syringe/syringe_stab_miss.ogg
sound/rust/arrow_ground.ogg
sound/rust/b17.ogg
sound/rust/b17_far.ogg
sound/rust/bars_metal_place.ogg
sound/rust/bars_wood_place.ogg
sound/rust/bow_cancel.ogg
sound/rust/bow_draw.ogg
sound/rust/bow_shoot.ogg
sound/rust/break_metal.ogg
sound/rust/break_metal3.ogg
sound/rust/break_metal4.ogg
sound/rust/break_stone.ogg
sound/rust/break_stone2.ogg
sound/rust/break_stone3.ogg
sound/rust/break_stone4.ogg
sound/rust/break_wood.ogg
sound/rust/break_wood2.ogg
sound/rust/break_wood3.ogg
sound/rust/break_wood4.ogg
sound/rust/build1.ogg
sound/rust/build2.ogg
sound/rust/burning3_short.ogg
sound/rust/c4_beep.wav
sound/rust/c4_plant.wav
sound/rust/code_lock_beep.ogg
sound/rust/code_lock_denied.ogg
sound/rust/code_lock_place.ogg
sound/rust/code_lock_shock.ogg
sound/rust/code_lock_update.ogg
sound/rust/damage_metal.ogg
sound/rust/damage_metal2.ogg
sound/rust/damage_metal3.ogg
sound/rust/damage_stone.ogg
sound/rust/damage_stone2.ogg
sound/rust/damage_stone3.ogg
sound/rust/damage_wood.ogg
sound/rust/damage_wood2.ogg
sound/rust/door_metal_close.ogg
sound/rust/door_metal_close2.ogg
sound/rust/door_metal_open.ogg
sound/rust/door_metal_place.ogg
sound/rust/door_wood_close.ogg
sound/rust/door_wood_open.ogg
sound/rust/door_wood_place.ogg
sound/rust/flame_on.ogg
sound/rust/flame_reload.ogg
sound/rust/flesh1.ogg
sound/rust/flesh2.ogg
sound/rust/flesh3.ogg
sound/rust/fuse.ogg
sound/rust/guitar.ogg
sound/rust/guitar2.ogg
sound/rust/hammer_swing.ogg
sound/rust/heli_far.ogg
sound/rust/high_wall_place_stone.ogg
sound/rust/high_wall_place_wood.ogg
sound/rust/ladder_hatch_close.ogg
sound/rust/ladder_hatch_open.ogg
sound/rust/ladder_hatch_place.ogg
sound/rust/ladder_place.ogg
sound/rust/metal_hatchet_wood.ogg
sound/rust/metal_pick_stone.ogg
sound/rust/metal_pick_swing.ogg
sound/rust/repair_metal.ogg
sound/rust/repair_metal2.ogg
sound/rust/repair_stone.ogg
sound/rust/repair_stone2.ogg
sound/rust/repair_wood.ogg
sound/rust/shutters_wood_close.ogg
sound/rust/shutters_wood_open.ogg
sound/rust/shutters_wood_place.ogg
sound/rust/sizzle.ogg
sound/rust/stone_axe_swing.ogg
sound/rust/stone_hatchet_wood.ogg
sound/rust/stone_pick_stone.ogg
sound/rust/stone_pick_stone2.ogg
sound/rust/stone_pick_stone3.ogg
sound/rust/stone_pick_stone4.ogg
sound/rust/stone_swing.ogg
sound/rust/stone_tree.ogg
sound/rust/tool_cupboard_place.ogg
sound/rust/upgrade_metal.ogg
sound/rust/upgrade_metal2.ogg
sound/rust/upgrade_metal3.ogg
sound/rust/upgrade_stone.ogg
sound/rust/upgrade_stone2.ogg
sound/rust/upgrade_stone3.ogg
sound/w00tguy/botrace/boo.wav
sound/w00tguy/botrace/yay.wav
sprites/rust/hud_rust.spr
sprites/rust/hud_rust2.spr
sprites/rust/hud_rust3.spr
sprites/rust/hud_rust4.spr
sprites/rust/rust_mini_b9_fix.spr
sprites/rust/map_plr.spr
sprites/rust/menu.spr
sprites/rust/weapon_bow.txt
sprites/rust/weapon_building_plan.txt
sprites/rust/weapon_custom_c4.txt
sprites/rust/weapon_custom_crowbar.txt
sprites/rust/weapon_custom_deagle.txt
sprites/rust/weapon_custom_grenade.txt
sprites/rust/weapon_custom_rpg.txt
sprites/rust/weapon_custom_saw.txt
sprites/rust/weapon_custom_shotgun.txt
sprites/rust/weapon_custom_sniper.txt
sprites/rust/weapon_custom_uzi.txt
sprites/rust/weapon_flamethrower.txt
sprites/rust/weapon_guitar.txt
sprites/rust/weapon_hammer.txt
sprites/rust/weapon_metal_hatchet.txt
sprites/rust/weapon_metal_pickaxe.txt
sprites/rust/weapon_rock.txt
sprites/rust/weapon_satchel_charge.txt
sprites/rust/weapon_stone_hatchet.txt
sprites/rust/weapon_stone_pickaxe.txt
sprites/rust/weapon_syringe.txt
