gfx/env/daylightup.tga
gfx/env/daylightdn.tga
gfx/env/daylightlf.tga
gfx/env/daylightrt.tga
gfx/env/daylightft.tga
gfx/env/daylightbk.tga
sound/xn/splash.wav
sound/xn/nicewater.wav
models/xn/forklift_driverless.mdl
sprites/xn/number_0.spr
sprites/xn/number_1.spr
sprites/xn/number_2.spr
sprites/xn/number_3.spr
sprites/xn/number_4.spr
sprites/xn/number_5.spr
sprites/xn/number_6.spr
sprites/xn/number_7.spr
sprites/xn/number_8.spr
sprites/xn/number_9.spr
