// Created with resguy v8 (September 2018)
// https://github.com/wootguy/resguy

models/sc_royals/crazybarney.mdl
models/sc_royals/headcrabp.mdl
models/sc_royals/houndeyep.mdl
models/sc_royals/islavep.mdl
models/sc_royals/mummy.mdl
models/sc_royals/mummy01.mdl
models/sc_royals/mummy02.mdl
models/sc_royals/mummyT.mdl
models/sc_royals/palm1a.mdl
models/sc_royals/palm2.mdl
models/sc_royals/rockgibsgold.mdl
models/sc_royals/sc_royals_model1.mdl
models/sc_royals/sc_royals_model2.mdl
models/sc_royals/sc_royals_model3.mdl
models/sc_royals/Torp.mdl
sound/sc_royals/blade.wav
sound/sc_royals/chant1.wav
sound/sc_royals/damn.wav
sound/sc_royals/deadscrm.wav
sound/sc_royals/gogogo.wav
sound/sc_royals/imsorry.wav
sound/sc_royals/laugh4.wav
sound/sc_royals/laugh5.wav
sound/sc_royals/mummy_alert1.wav
sound/sc_royals/mummy_alert2.wav
sound/sc_royals/mummy_alert3.wav
sound/sc_royals/mummy_attack1.wav
sound/sc_royals/mummy_attack2.wav
sound/sc_royals/mummy_idle1.wav
sound/sc_royals/mummy_idle2.wav
sound/sc_royals/mummy_idle3.wav
sound/sc_royals/mummy_idle4.wav
sound/sc_royals/mummy_pain1.wav
sound/sc_royals/mummy_pain2.wav
sound/sc_royals/music_general.mp3
sound/sc_royals/thatsit.wav
sound/sc_royals/yoga.wav
