// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

Armymen.wad
models/player/Armyman_Grunt/Armyman_Grunt.mdl
models/player/Armyman_Medic/Armyman_Medic.mdl
models/player/Armyman_Shotgun/Armyman_Shotgun.mdl
models/player/Armyman_Sniper/Armyman_Sniper.mdl
models/player/Armyman_Tower/Armyman_Tower.mdl
models/sc_toysoldiers/misc/agibs.mdl
models/sc_toysoldiers/misc/flag.mdl
models/sc_toysoldiers/misc/hgibs.mdl
models/sc_toysoldiers/misc/sandbags_green.mdl
models/sc_toysoldiers/misc/sandbags_tan.mdl
models/sc_toysoldiers/monsters/apache_tan.mdl
models/sc_toysoldiers/monsters/bgman.mdl
models/sc_toysoldiers/monsters/fgrunt.mdl
models/sc_toysoldiers/monsters/fgruntf.mdl
models/sc_toysoldiers/monsters/hgrunt.mdl
models/sc_toysoldiers/monsters/hgrunt_flame.mdl
models/sc_toysoldiers/monsters/hgrunt_medic.mdl
models/sc_toysoldiers/monsters/hgrunt_medicf.mdl
models/sc_toysoldiers/monsters/hgruntf.mdl
models/sc_toysoldiers/monsters/hgruntg.mdl
models/sc_toysoldiers/monsters/huey.mdl
models/sc_toysoldiers/monsters/hueyT.mdl
models/sc_toysoldiers/monsters/hwgrunt.mdl
models/sc_toysoldiers/monsters/massn.mdl
models/sc_toysoldiers/monsters/osprey_tan.mdl
models/sc_toysoldiers/monsters/Pilot.mdl
models/sc_toysoldiers/monsters/sentry.mdl
models/sc_toysoldiers/monsters/sniper.mdl
models/sc_toysoldiers/weapons/armor.mdl
models/sc_toysoldiers/weapons/grenade.mdl
models/sc_toysoldiers/weapons/p_2uzis.mdl
models/sc_toysoldiers/weapons/p_2uzis_gold.mdl
models/sc_toysoldiers/weapons/p_357.mdl
models/sc_toysoldiers/weapons/p_9mmAR.mdl
models/sc_toysoldiers/weapons/p_9mmhandgun.mdl
models/sc_toysoldiers/weapons/p_crossbow.mdl
models/sc_toysoldiers/weapons/p_desert_eagle.mdl
models/sc_toysoldiers/weapons/p_grenade.mdl
models/sc_toysoldiers/weapons/p_knife.mdl
models/sc_toysoldiers/weapons/p_m16a2.mdl
models/sc_toysoldiers/weapons/p_m40a1.mdl
models/sc_toysoldiers/weapons/p_medkit.mdl
models/sc_toysoldiers/weapons/p_minigunidle.mdl
models/sc_toysoldiers/weapons/p_minigunspin.mdl
models/sc_toysoldiers/weapons/p_rpg.mdl
models/sc_toysoldiers/weapons/p_saw.mdl
models/sc_toysoldiers/weapons/p_shotgun.mdl
models/sc_toysoldiers/weapons/p_uzi.mdl
models/sc_toysoldiers/weapons/p_uzi_gold.mdl
models/sc_toysoldiers/weapons/saw_link.mdl
models/sc_toysoldiers/weapons/saw_shell.mdl
models/sc_toysoldiers/weapons/shell.mdl
models/sc_toysoldiers/weapons/shotgunshell.mdl
models/sc_toysoldiers/weapons/v_357.mdl
models/sc_toysoldiers/weapons/v_9mmar.mdl
models/sc_toysoldiers/weapons/v_9mmhandgun.mdl
models/sc_toysoldiers/weapons/v_crossbow.mdl
models/sc_toysoldiers/weapons/v_desert_eagle.mdl
models/sc_toysoldiers/weapons/v_grenade.mdl
models/sc_toysoldiers/weapons/v_knife.mdl
models/sc_toysoldiers/weapons/v_m16a2.mdl
models/sc_toysoldiers/weapons/v_m40a1.mdl
models/sc_toysoldiers/weapons/v_medkit.mdl
models/sc_toysoldiers/weapons/v_minigun.mdl
models/sc_toysoldiers/weapons/v_rpg.mdl
models/sc_toysoldiers/weapons/v_saw.mdl
models/sc_toysoldiers/weapons/v_sawT.mdl
models/sc_toysoldiers/weapons/v_shotgun.mdl
models/sc_toysoldiers/weapons/v_uzi.mdl
models/sc_toysoldiers/weapons/w_2uzis.mdl
models/sc_toysoldiers/weapons/w_2uzis_gold.mdl
models/sc_toysoldiers/weapons/w_357.mdl
models/sc_toysoldiers/weapons/w_357ammo.mdl
models/sc_toysoldiers/weapons/w_357ammobox.mdl
models/sc_toysoldiers/weapons/w_9mmar.mdl
models/sc_toysoldiers/weapons/w_9mmarclip.mdl
models/sc_toysoldiers/weapons/w_9mmclip.mdl
models/sc_toysoldiers/weapons/w_9mmhandgun.mdl
models/sc_toysoldiers/weapons/w_9mmhandgunt.mdl
models/sc_toysoldiers/weapons/w_argrenade.mdl
models/sc_toysoldiers/weapons/w_chainammo.mdl
models/sc_toysoldiers/weapons/w_crossbow.mdl
models/sc_toysoldiers/weapons/w_crossbow_clip.mdl
models/sc_toysoldiers/weapons/w_desert_eagle.mdl
models/sc_toysoldiers/weapons/w_grenade.mdl
models/sc_toysoldiers/weapons/w_knife.mdl
models/sc_toysoldiers/weapons/w_m16a2.mdl
models/sc_toysoldiers/weapons/w_m40a1.mdl
models/sc_toysoldiers/weapons/w_m40a1clip.mdl
models/sc_toysoldiers/weapons/w_medkit.mdl
models/sc_toysoldiers/weapons/w_minigun.mdl
models/sc_toysoldiers/weapons/w_mp5_clip.mdl
models/sc_toysoldiers/weapons/w_rpg.mdl
models/sc_toysoldiers/weapons/w_rpgammo.mdl
models/sc_toysoldiers/weapons/w_saw.mdl
models/sc_toysoldiers/weapons/w_saw_clip.mdl
models/sc_toysoldiers/weapons/w_shotbox.mdl
models/sc_toysoldiers/weapons/w_shotgun.mdl
models/sc_toysoldiers/weapons/w_uzi.mdl
models/sc_toysoldiers/weapons/w_uzi_clip.mdl
models/sc_toysoldiers/weapons/w_uzi_gold.mdl
sound/sc_toysoldiers/bcry.wav
sound/sc_toysoldiers/deathfall.wav
sound/sc_toysoldiers/endgame.wav
sound/sc_toysoldiers/fgrunt/area.wav
sound/sc_toysoldiers/fgrunt/ass.wav
sound/sc_toysoldiers/fgrunt/babysitting.wav
sound/sc_toysoldiers/fgrunt/backup.wav
sound/sc_toysoldiers/fgrunt/bfeeling.wav
sound/sc_toysoldiers/fgrunt/bogies.wav
sound/sc_toysoldiers/fgrunt/charge.wav
sound/sc_toysoldiers/fgrunt/check.wav
sound/sc_toysoldiers/fgrunt/checkrecon.wav
sound/sc_toysoldiers/fgrunt/chicken.wav
sound/sc_toysoldiers/fgrunt/clear.wav
sound/sc_toysoldiers/fgrunt/command.wav
sound/sc_toysoldiers/fgrunt/corners.wav
sound/sc_toysoldiers/fgrunt/corporal_01.wav
sound/sc_toysoldiers/fgrunt/cover.wav
sound/sc_toysoldiers/fgrunt/critical.wav
sound/sc_toysoldiers/fgrunt/current.wav
sound/sc_toysoldiers/fgrunt/death1.wav
sound/sc_toysoldiers/fgrunt/death2.wav
sound/sc_toysoldiers/fgrunt/death3.wav
sound/sc_toysoldiers/fgrunt/down.wav
sound/sc_toysoldiers/fgrunt/fire.wav
sound/sc_toysoldiers/fgrunt/flank.wav
sound/sc_toysoldiers/fgrunt/freaks.wav
sound/sc_toysoldiers/fgrunt/fubar.wav
sound/sc_toysoldiers/fgrunt/fwound.wav
sound/sc_toysoldiers/fgrunt/getsome.wav
sound/sc_toysoldiers/fgrunt/go.wav
sound/sc_toysoldiers/fgrunt/grenade.wav
sound/sc_toysoldiers/fgrunt/guard.wav
sound/sc_toysoldiers/fgrunt/hear.wav
sound/sc_toysoldiers/fgrunt/hearsome.wav
sound/sc_toysoldiers/fgrunt/hitbad.wav
sound/sc_toysoldiers/fgrunt/hostiles.wav
sound/sc_toysoldiers/fgrunt/hurt.wav
sound/sc_toysoldiers/fgrunt/imhit.wav
sound/sc_toysoldiers/fgrunt/incoming.wav
sound/sc_toysoldiers/fgrunt/lost.wav
sound/sc_toysoldiers/fgrunt/makeit.wav
sound/sc_toysoldiers/fgrunt/medic.wav
sound/sc_toysoldiers/fgrunt/mission.wav
sound/sc_toysoldiers/fgrunt/mister.wav
sound/sc_toysoldiers/fgrunt/move.wav
sound/sc_toysoldiers/fgrunt/needmedic.wav
sound/sc_toysoldiers/fgrunt/nothing.wav
sound/sc_toysoldiers/fgrunt/onepiece.wav
sound/sc_toysoldiers/fgrunt/oneshot.wav
sound/sc_toysoldiers/fgrunt/orders.wav
sound/sc_toysoldiers/fgrunt/pain1.wav
sound/sc_toysoldiers/fgrunt/pain2.wav
sound/sc_toysoldiers/fgrunt/pain3.wav
sound/sc_toysoldiers/fgrunt/pain4.wav
sound/sc_toysoldiers/fgrunt/pain5.wav
sound/sc_toysoldiers/fgrunt/rapidfire.wav
sound/sc_toysoldiers/fgrunt/recon.wav
sound/sc_toysoldiers/fgrunt/secure.wav
sound/sc_toysoldiers/fgrunt/seensquad.wav
sound/sc_toysoldiers/fgrunt/sir_01.wav
sound/sc_toysoldiers/fgrunt/siryessir.wav
sound/sc_toysoldiers/fgrunt/situations.wav
sound/sc_toysoldiers/fgrunt/staydown.wav
sound/sc_toysoldiers/fgrunt/sting.wav
sound/sc_toysoldiers/fgrunt/suppressing.wav
sound/sc_toysoldiers/fgrunt/tag.wav
sound/sc_toysoldiers/fgrunt/take.wav
sound/sc_toysoldiers/fgrunt/talking.wav
sound/sc_toysoldiers/fgrunt/through.wav
sound/sc_toysoldiers/fgrunt/wantsome.wav
sound/sc_toysoldiers/fgrunt/watchfire.wav
sound/sc_toysoldiers/fgrunt/watchit.wav
sound/sc_toysoldiers/fgrunt/zone.wav
sound/sc_toysoldiers/hgrunt/_comma.wav
sound/sc_toysoldiers/hgrunt/alert.wav
sound/sc_toysoldiers/hgrunt/allclear.wav
sound/sc_toysoldiers/hgrunt/area.wav
sound/sc_toysoldiers/hgrunt/backup.wav
sound/sc_toysoldiers/hgrunt/bogies.wav
sound/sc_toysoldiers/hgrunt/charge.wav
sound/sc_toysoldiers/hgrunt/check.wav
sound/sc_toysoldiers/hgrunt/corners.wav
sound/sc_toysoldiers/hgrunt/cover.wav
sound/sc_toysoldiers/hgrunt/current.wav
sound/sc_toysoldiers/hgrunt/death1.wav
sound/sc_toysoldiers/hgrunt/death2.wav
sound/sc_toysoldiers/hgrunt/death3.wav
sound/sc_toysoldiers/hgrunt/down.wav
sound/sc_toysoldiers/hgrunt/fire.wav
sound/sc_toysoldiers/hgrunt/getsome.wav
sound/sc_toysoldiers/hgrunt/go.wav
sound/sc_toysoldiers/hgrunt/grenade.wav
sound/sc_toysoldiers/hgrunt/hostiles.wav
sound/sc_toysoldiers/hgrunt/incoming.wav
sound/sc_toysoldiers/hgrunt/mission.wav
sound/sc_toysoldiers/hgrunt/mister.wav
sound/sc_toysoldiers/hgrunt/move.wav
sound/sc_toysoldiers/hgrunt/moveup.wav
sound/sc_toysoldiers/hgrunt/nohostiles.wav
sound/sc_toysoldiers/hgrunt/nomovement.wav
sound/sc_toysoldiers/hgrunt/nothing.wav
sound/sc_toysoldiers/hgrunt/of6a1_fg02.wav
sound/sc_toysoldiers/hgrunt/oneshot.wav
sound/sc_toysoldiers/hgrunt/pain1.wav
sound/sc_toysoldiers/hgrunt/pain2.wav
sound/sc_toysoldiers/hgrunt/pain3.wav
sound/sc_toysoldiers/hgrunt/pain4.wav
sound/sc_toysoldiers/hgrunt/pain5.wav
sound/sc_toysoldiers/hgrunt/retreat.wav
sound/sc_toysoldiers/hgrunt/stayalert.wav
sound/sc_toysoldiers/hgrunt/staydown.wav
sound/sc_toysoldiers/hgrunt/take.wav
sound/sc_toysoldiers/hgrunt/takecover.wav
sound/sc_toysoldiers/hgrunt/wantsome.wav
sound/sc_toysoldiers/hgrunt/zone.wav
sound/sc_toysoldiers/radio1.wav
sound/sc_toysoldiers/radio2.wav
sound/sc_toysoldiers/radio3.wav
sound/sc_toysoldiers/radio4.wav
sound/sc_toysoldiers/radio_intro.wav
sound/sc_toysoldiers/radio_message1.wav
sound/sc_toysoldiers/radio_message2.wav
sound/sc_toysoldiers/radio_start.wav
sound/sc_toysoldiers/rotors.wav
sound/sc_toysoldiers/train.wav
sound/sc_toysoldiers/trooper/gar_alert1.wav
sound/sc_toysoldiers/trooper/gar_alert2.wav
sound/sc_toysoldiers/trooper/gar_alert3.wav
sound/sc_toysoldiers/trooper/gar_attack1.wav
sound/sc_toysoldiers/trooper/gar_attack2.wav
sound/sc_toysoldiers/trooper/gar_attack3.wav
sound/sc_toysoldiers/trooper/gar_breathe1.wav
sound/sc_toysoldiers/trooper/gar_breathe2.wav
sound/sc_toysoldiers/trooper/gar_breathe3.wav
sound/sc_toysoldiers/trooper/gar_die1.wav
sound/sc_toysoldiers/trooper/gar_die2.wav
sound/sc_toysoldiers/trooper/gar_idle1.wav
sound/sc_toysoldiers/trooper/gar_idle2.wav
sound/sc_toysoldiers/trooper/gar_idle3.wav
sound/sc_toysoldiers/trooper/gar_idle4.wav
sound/sc_toysoldiers/trooper/gar_idle5.wav
sound/sc_toysoldiers/trooper/gar_pain1.wav
sound/sc_toysoldiers/trooper/gar_pain2.wav
sound/sc_toysoldiers/trooper/gar_pain3.wav
sound/sc_toysoldiers/trooper/gar_step1.wav
sound/sc_toysoldiers/trooper/gar_step2.wav
sound/sc_toysoldiers/trooper/gar_stomp1.wav
sound/sc_toysoldiers/woops.wav
