maps/sc_tombofdeath_v12-5.res
maps/sc_tombofdeath_v12-5.bsp
maps/sc_tombofdeath_v12-5.cfg
maps/sc_tombofdeath_v12-5_skl.cfg
maps/sc_tombofdeath_v12-5_motd.txt
models/sc_tombofdeath/w_suit.mdl
models/sc_tombofdeath/bloodgonome.mdl
models/sc_tombofdeath/pitdrone.mdl
models/sc_tombofdeath/pitdrone_gibs.mdl
sc_tombofdeath_readme.txt
sc_tombofdeath.wad