// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/blkops/bgman.mdl
models/blkops/v_357.mdl
models/blkops/v_9mmar.mdl
models/blkops/v_9mmhandgun.mdl
models/blkops/v_chub.mdl
models/blkops/v_crossbow.mdl
models/blkops/v_desert_eagle.mdl
models/blkops/v_displacer.mdl
models/blkops/v_egon.mdl
models/blkops/v_gauss.mdl
models/blkops/v_grenade.mdl
models/blkops/v_knife.mdl
models/blkops/v_m16a2.mdl
models/blkops/v_m40a1.mdl
models/blkops/v_medkit.mdl
models/blkops/v_pipe_wrench.mdl
models/blkops/v_rpg.mdl
models/blkops/v_satchel.mdl
models/blkops/v_satchel_radio.mdl
models/blkops/v_saw.mdl
models/blkops/v_shotgun.mdl
models/blkops/v_spore_launcher.mdl
models/blkops/v_squeak.mdl
models/blkops/v_tripmine.mdl
models/blkops/v_uzi.mdl
models/player/aswatblack/aswatblack.bmp
models/player/aswatblack/aswatblack.mdl
models/player/bodyguard/bodyguard.bmp
models/player/bodyguard/bodyguard.mdl
models/player/bodyguard2/bodyguard2.bmp
models/player/bodyguard2/bodyguard2.mdl
models/player/massn_black/massn_black.bmp
models/player/massn_black/massn_black.mdl
models/player/splintercell/splintercell.bmp
models/player/splintercell/splintercell.mdl
models/player/splintercell_red/splintercell_red.bmp
models/player/splintercell_red/splintercell_red.mdl
ul.wad
