// Created with resguy v6 (November 2017)
// https://github.com/wootguy/resguy

models/uboa45/abababa.mdl
models/uboa45/babyshii.mdl
models/uboa45/cat.mdl
models/uboa45/electro.mdl
models/uboa45/gamern.mdl
models/uboa45/gamert.mdl
models/uboa45/knifer.mdl
models/uboa45/knifer01.mdl
models/uboa45/kumaa.mdl
models/uboa45/morimaki.mdl
models/uboa45/rausde.mdl
models/uboa45/saitama.mdl
models/uboa45/shii.mdl
models/uboa45/sin.mdl
models/uboa45/speed.mdl
models/uboa45/speed01.mdl
models/uboa45/uboa1.mdl
models/uboa45/uboa1b.mdl
models/uboa45/uribou.mdl
sound/uboa45/abababa/alert10.wav
sound/uboa45/abababa/alert20.wav
sound/uboa45/abababa/alert30.wav
sound/uboa45/abababa/attack10.wav
sound/uboa45/abababa/attack20.wav
sound/uboa45/abababa/idle1.wav
sound/uboa45/abababa/idle2.wav
sound/uboa45/abababa/idle3.wav
sound/uboa45/abababa/idle4.wav
sound/uboa45/abababa/miss1.wav
sound/uboa45/abababa/miss2.wav
sound/uboa45/abababa/pain1.wav
sound/uboa45/abababa/pain2.wav
sound/uboa45/abababa/strike1.wav
sound/uboa45/abababa/strike2.wav
sound/uboa45/abababa/strike3.wav
sound/uboa45/babyshii/alert1.wav
sound/uboa45/babyshii/alert2.wav
sound/uboa45/babyshii/attack1.wav
sound/uboa45/babyshii/attack2.wav
sound/uboa45/babyshii/attack3.wav
sound/uboa45/babyshii/idle1.wav
sound/uboa45/babyshii/idle2.wav
sound/uboa45/babyshii/idle3.wav
sound/uboa45/babyshii/pain1.wav
sound/uboa45/babyshii/pain2.wav
sound/uboa45/babyshii/pain3.wav
sound/uboa45/bgm_clear.wav
sound/uboa45/bgm_fart.wav
sound/uboa45/bgm_loop.wav
sound/uboa45/bgm_result1.wav
sound/uboa45/bgm_result2.wav
sound/uboa45/bgm_result3.wav
sound/uboa45/bgm_result4.wav
sound/uboa45/bgm_start.wav
sound/uboa45/bgm_timeout.wav
sound/uboa45/cat/nyaaa.wav
sound/uboa45/electro/attack1.wav
sound/uboa45/electro/attack2.wav
sound/uboa45/electro/attack3.wav
sound/uboa45/electro/die1.wav
sound/uboa45/electro/die2.wav
sound/uboa45/electro/idle1.wav
sound/uboa45/electro/idle2.wav
sound/uboa45/electro/idle3.wav
sound/uboa45/electro/pain01.wav
sound/uboa45/electro/pain02.wav
sound/uboa45/electro/pain03.wav
sound/uboa45/electro/stomp1.wav
sound/uboa45/gamer/alert1.wav
sound/uboa45/gamer/alert2.wav
sound/uboa45/gamer/alert3.wav
sound/uboa45/gamer/attack1.wav
sound/uboa45/gamer/attack2.wav
sound/uboa45/gamer/getouthere.wav
sound/uboa45/gamer/idle1.wav
sound/uboa45/gamer/idle2.wav
sound/uboa45/gamer/idle3.wav
sound/uboa45/gamer/idle4.wav
sound/uboa45/gamer/pain1.wav
sound/uboa45/gamer/pain2.wav
sound/uboa45/gamer/strike.wav
sound/uboa45/knifer/attack.wav
sound/uboa45/knifer/miss.wav
sound/uboa45/rausde/idiot.wav
sound/uboa45/saitama/alert1.wav
sound/uboa45/saitama/alert2.wav
sound/uboa45/saitama/alert3.wav
sound/uboa45/saitama/death2.wav
sound/uboa45/saitama/death3.wav
sound/uboa45/saitama/death4.wav
sound/uboa45/saitama/eat.wav
sound/uboa45/saitama/idle1.wav
sound/uboa45/saitama/idle2.wav
sound/uboa45/saitama/idle3.wav
sound/uboa45/saitama/melee1.wav
sound/uboa45/saitama/melee2.wav
sound/uboa45/saitama/miss.wav
sound/uboa45/saitama/null.wav
sound/uboa45/saitama/pain1.wav
sound/uboa45/saitama/pain2.wav
sound/uboa45/saitama/pain3.wav
sound/uboa45/saitama/pain4.wav
sound/uboa45/saitama/strike.wav
sound/uboa45/shii/alert1.wav
sound/uboa45/shii/alert2.wav
sound/uboa45/shii/alert3.wav
sound/uboa45/shii/attack1.wav
sound/uboa45/shii/attack2.wav
sound/uboa45/shii/idle1.wav
sound/uboa45/shii/idle2.wav
sound/uboa45/shii/idle3.wav
sound/uboa45/shii/idle4.wav
sound/uboa45/shii/miss1.wav
sound/uboa45/shii/miss2.wav
sound/uboa45/shii/pain1.wav
sound/uboa45/shii/pain2.wav
sound/uboa45/shii/strike.wav
sound/uboa45/sin/alert1.wav
sound/uboa45/sin/alert2.wav
sound/uboa45/sin/alert3.wav
sound/uboa45/sin/attack1.wav
sound/uboa45/sin/attack2.wav
sound/uboa45/sin/idle1.wav
sound/uboa45/sin/idle2.wav
sound/uboa45/sin/idle3.wav
sound/uboa45/sin/idle4.wav
sound/uboa45/sin/miss.wav
sound/uboa45/sin/pain1.wav
sound/uboa45/sin/pain2.wav
sound/uboa45/sin/strike.wav
sound/votemap/kumaa/alert1.wav
sound/votemap/kumaa/alert2.wav
sound/votemap/kumaa/alert3.wav
sound/votemap/kumaa/death1.wav
sound/votemap/kumaa/death2.wav
sound/votemap/kumaa/idle1.wav
sound/votemap/kumaa/idle2.wav
sound/votemap/kumaa/idle3.wav
sound/votemap/kumaa/idle4.wav
sound/votemap/kumaa/idle5.wav
sound/votemap/kumaa/pain1.wav
sound/votemap/kumaa/pain2.wav
sound/votemap/kumaa/pain3.wav
sound/votemap/saitama/miss.wav
