maps/uboa_rampage_II.bsp
maps/uboa_rampage_II.cfg
maps/uboa_rampage_II_motd.txt
models/pizza_ya_san/gamesaba.mdl
models/player/uboac_rampage2_p1/uboac_rampage2_p1.bmp
models/player/uboac_rampage2_p1/uboac_rampage2_p1.mdl
models/player/uboac_rampage2_p2/uboac_rampage2_p2.bmp
models/player/uboac_rampage2_p2/uboac_rampage2_p2.mdl
models/player/uboac_rampage2_p3/uboac_rampage2_p3.bmp
models/player/uboac_rampage2_p3/uboac_rampage2_p3.mdl
models/player/uboac_rampage2_p4/uboac_rampage2_p4.bmp
models/player/uboac_rampage2_p4/uboac_rampage2_p4.mdl
models/player/uboac/uboa_color.txt
models/player/uboac/uboac.bmp
models/player/uboac/uboac.mdl
models/uboa_rampage_II/armored_uboa.mdl
models/uboa_rampage_II/bifizus.mdl
models/uboa_rampage_II/biofermin.mdl
models/uboa_rampage_II/biofermintake.mdl
models/uboa_rampage_II/brutal_konichiwa.mdl
models/uboa_rampage_II/electro_black.mdl
models/uboa_rampage_II/electro_dougi.mdl
models/uboa_rampage_II/fusasaba.mdl
models/uboa_rampage_II/kemushi.mdl
models/uboa_rampage_II/models.txt
models/uboa_rampage_II/morimaki2d.mdl
models/uboa_rampage_II/morimen.mdl
models/uboa_rampage_II/onsen_enuze.mdl
models/uboa_rampage_II/p_block.mdl
models/uboa_rampage_II/p_butterflyknife.mdl
models/uboa_rampage_II/p_gennou.mdl
models/uboa_rampage_II/p_golfclub.mdl
models/uboa_rampage_II/p_guidelight.mdl
models/uboa_rampage_II/p_higonokami.mdl
models/uboa_rampage_II/p_ironpipe.mdl
models/uboa_rampage_II/p_kagizume.mdl
models/uboa_rampage_II/p_kanban.mdl
models/uboa_rampage_II/p_karateglove.mdl
models/uboa_rampage_II/p_katana.mdl
models/uboa_rampage_II/p_kitchenknife.mdl
models/uboa_rampage_II/p_kukri.mdl
models/uboa_rampage_II/p_lucille.mdl
models/uboa_rampage_II/p_merikensack2.mdl
models/uboa_rampage_II/p_pickaxe.mdl
models/uboa_rampage_II/p_policebaton.mdl
models/uboa_rampage_II/p_sude.mdl
models/uboa_rampage_II/p_tekkotsu.mdl
models/uboa_rampage_II/p_zassi.mdl
models/uboa_rampage_II/rirekisho.mdl
models/uboa_rampage_II/swordwave.mdl
models/uboa_rampage_II/throwknife.mdl
models/uboa_rampage_II/v_block.mdl
models/uboa_rampage_II/v_butterflyknife.mdl
models/uboa_rampage_II/v_gennou.mdl
models/uboa_rampage_II/v_golfclub.mdl
models/uboa_rampage_II/v_guidelight.mdl
models/uboa_rampage_II/v_higonokami.mdl
models/uboa_rampage_II/v_ironpipe.mdl
models/uboa_rampage_II/v_kagizume.mdl
models/uboa_rampage_II/v_kanban.mdl
models/uboa_rampage_II/v_karateglove.mdl
models/uboa_rampage_II/v_katana.mdl
models/uboa_rampage_II/v_kitchenknife.mdl
models/uboa_rampage_II/v_kukri.mdl
models/uboa_rampage_II/v_lucille.mdl
models/uboa_rampage_II/v_merikensack2.mdl
models/uboa_rampage_II/v_pickaxe.mdl
models/uboa_rampage_II/v_policebaton.mdl
models/uboa_rampage_II/v_sude.mdl
models/uboa_rampage_II/v_tekkotsu.mdl
models/uboa_rampage_II/v_zassi.mdl
models/uboa_rampage_II/w_block.mdl
models/uboa_rampage_II/w_butterflyknife.mdl
models/uboa_rampage_II/w_gennou.mdl
models/uboa_rampage_II/w_golfclub.mdl
models/uboa_rampage_II/w_guidelight.mdl
models/uboa_rampage_II/w_higonokami.mdl
models/uboa_rampage_II/w_ironpipe.mdl
models/uboa_rampage_II/w_kagizume.mdl
models/uboa_rampage_II/w_kanban.mdl
models/uboa_rampage_II/w_karateglove.mdl
models/uboa_rampage_II/w_katana.mdl
models/uboa_rampage_II/w_kitchenknife.mdl
models/uboa_rampage_II/w_kukri.mdl
models/uboa_rampage_II/w_lucille.mdl
models/uboa_rampage_II/w_merikensack2.mdl
models/uboa_rampage_II/w_pickaxe.mdl
models/uboa_rampage_II/w_policebaton.mdl
models/uboa_rampage_II/w_sude.mdl
models/uboa_rampage_II/w_tekkotsu.mdl
models/uboa_rampage_II/w_zassi.mdl
models/uboa_rampage/akikan.mdl
models/uboa_rampage/imomushi.mdl
models/uboa_rampage/konichiwa.mdl
models/uboa_rampage/morimaki_melee.mdl
models/uboa_rampage/morimaki_meleeT.mdl
models/uboa_rampage/nnmad.mdl
models/uboa_rampage/p_medkit.mdl
models/uboa_rampage/pi_tree.mdl
models/uboa_rampage/ripoD.mdl
models/uboa_rampage/sake.mdl
models/uboa_rampage/sincube.mdl
models/uboa_rampage/uboazombie.mdl
models/uboa_rampage/uboazombie01.mdl
models/uboa_rampage/uboazombie02.mdl
models/uboa_rampage/uboazombie03.mdl
models/uboa_rampage/uboazombieT.mdl
models/uboa_rampage/v_medkit.mdl
models/uboa_rampage/w_pmedkit.mdl
models/uboa45/sin.mdl
sound/takedeppo/50cal_fire.wav
sound/takedeppo/50cal_fun_time.wav
sound/uboa_rampage_II/bgm_maoudamashii_neorock32_loop.mp3
sound/uboa_rampage_II/bgm_maoudamashii_neorock63_loop.mp3
sound/uboa_rampage_II/bgm_maoudamashii_neorock76_loop.mp3
sound/uboa_rampage_II/bgm_maoudamashii_neorock78_loop.mp3
sound/uboa_rampage_II/bifizus.txt
sound/uboa_rampage_II/biofermin.txt
sound/uboa_rampage_II/bladeattack.wav
sound/uboa_rampage_II/chiisanatsubuno.wav
sound/uboa_rampage_II/chounaino.wav
sound/uboa_rampage_II/electro.txt
sound/uboa_rampage_II/geribenpi.wav
sound/uboa_rampage_II/hardattack.wav
sound/uboa_rampage_II/po-n.wav
sound/uboa_rampage_II/shinbioferminS.wav
sound/uboa_rampage_II/sokkadakara.wav
sound/uboa_rampage_II/soukonnakanji.wav
sound/uboa_rampage_II/sounds.txt
sound/uboa_rampage_II/strikeattack.wav
sound/uboa_rampage_II/swing.wav
sound/uboa_rampage_II/turnpage.wav
sound/uboa_rampage/acoustic38.ogg
sound/uboa_rampage/babygarg.txt
sound/uboa_rampage/bahhh.wav
sound/uboa_rampage/bishi.wav
sound/uboa_rampage/dareda.wav
sound/uboa_rampage/doka.wav
sound/uboa_rampage/imomushi.txt
sound/uboa_rampage/kichigai.wav
sound/uboa_rampage/konichiwa.txt
sound/uboa_rampage/koraa.wav
sound/uboa_rampage/nnmad.txt
sound/uboa_rampage/sunaa.wav
sound/uboa_rampage/uboa_h.wav
sound/uboa_rampage/uboazombie.txt
sound/uboa_rampage/uwaaa_h.wav
sound/uboa_rampage/waaa.wav
sound/uboa45/bgm_loop.wav
sound/uboa45/bgm_start.wav
sound/uboa45/electro/attack1.wav
sound/uboa45/electro/attack2.wav
sound/uboa45/electro/attack3.wav
sound/uboa45/electro/die1.wav
sound/uboa45/electro/die2.wav
sound/uboa45/electro/idle1.wav
sound/uboa45/electro/idle2.wav
sound/uboa45/electro/idle3.wav
sound/uboa45/electro/pain01.wav
sound/uboa45/electro/pain02.wav
sound/uboa45/electro/pain03.wav
sound/uboa45/electro/stomp1.wav
sound/uboa45/morimaki.txt
sound/uboa45/sin.txt
sound/uboa45/sin/alert1.wav
sound/uboa45/sin/alert2.wav
sound/uboa45/sin/alert3.wav
sound/uboa45/sin/attack1.wav
sound/uboa45/sin/attack2.wav
sound/uboa45/sin/idle1.wav
sound/uboa45/sin/idle2.wav
sound/uboa45/sin/idle3.wav
sound/uboa45/sin/idle4.wav
sound/uboa45/sin/miss.wav
sound/uboa45/sin/pain1.wav
sound/uboa45/sin/pain2.wav
sound/uboa45/sin/strike.wav
sound/votemap2/kyokushin_loop.ogg
sprites/uboa_rampage_II/ammoicon.spr
sprites/uboa_rampage_II/weapon_block.txt
sprites/uboa_rampage_II/weapon_butterflyknife.txt
sprites/uboa_rampage_II/weapon_gennou.txt
sprites/uboa_rampage_II/weapon_golfclub.txt
sprites/uboa_rampage_II/weapon_guidelight.txt
sprites/uboa_rampage_II/weapon_higonokami.txt
sprites/uboa_rampage_II/weapon_ironpipe.txt
sprites/uboa_rampage_II/weapon_kagizume.txt
sprites/uboa_rampage_II/weapon_kanban.txt
sprites/uboa_rampage_II/weapon_karateglove.txt
sprites/uboa_rampage_II/weapon_katana.txt
sprites/uboa_rampage_II/weapon_kitchenknife.txt
sprites/uboa_rampage_II/weapon_kukri.txt
sprites/uboa_rampage_II/weapon_lucille.txt
sprites/uboa_rampage_II/weapon_merikensack2.txt
sprites/uboa_rampage_II/weapon_pickaxe.txt
sprites/uboa_rampage_II/weapon_policebaton.txt
sprites/uboa_rampage_II/weapon_sude.txt
sprites/uboa_rampage_II/weapon_tekkotsu.txt
sprites/uboa_rampage_II/weapon_zassi.txt
sprites/uboa_rampage_II/weapon1.spr
sprites/uboa_rampage_II/weapon2.spr
sprites/uboa_rampage_II/weapon3.spr
sprites/uboa_rampage_II/weapon4.spr
sprites/uboa_rampage_II/weapon5.spr
sprites/uboa_rampage_II/weapon6.spr
sprites/uboa_rampage_II/weapon7.spr
sprites/uboa_rampage_II/weapon8.spr
