models/player/nsmbw_larry/nsmbw_larry.bmp
models/player/nsmbw_larry/nsmbw_larry.mdl
sound/ambience/liftmuzak.wav
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
sprites/hl_weapons/weapon_hl357.txt
models/hl/p_357.mdl
models/hl/v_357.mdl
models/hl/w_357.mdl
models/hl/w_357t.mdl
sound/hl/weapons/357_reload1.wav
sound/hl/weapons/357_shot1.wav
sound/hl/weapons/357_shot2.wav
sound/gta2/wasted.wav
