// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

models/ast/apc_turret.mdl
models/ast/gordon_massn2.mdl
models/ast/w_nvg.mdl
models/decay/dead_islave.mdl
models/opfor/svenhands/v_knife.mdl
models/opfor/wire_black32.mdl
models/opfor/wire_copper8.mdl
models/player/bfassn/bfassn.bmp
models/player/bfassn/bfassn.mdl
models/scmod/ast/weapons/p_357.mdl
models/scmod/ast/weapons/p_9mmar.mdl
models/scmod/ast/weapons/p_9mmhandgun.mdl
models/scmod/ast/weapons/p_crowbar.mdl
models/scmod/ast/weapons/p_desert_eagle.mdl
models/scmod/ast/weapons/p_grenade.mdl
models/scmod/ast/weapons/p_m16.mdl
models/scmod/ast/weapons/p_m40a1.mdl
models/scmod/ast/weapons/p_saw.mdl
models/scmod/ast/weapons/v_357.mdl
models/scmod/ast/weapons/v_9mmar.mdl
models/scmod/ast/weapons/v_9mmhandgun.mdl
models/scmod/ast/weapons/v_crowbar.mdl
models/scmod/ast/weapons/v_desert_eagle.mdl
models/scmod/ast/weapons/v_grenade.mdl
models/scmod/ast/weapons/v_m16a2.mdl
models/scmod/ast/weapons/v_m40a1.mdl
models/scmod/ast/weapons/v_saw.mdl
models/scmod/ast/weapons/w_357.mdl
models/scmod/ast/weapons/w_9mmar.mdl
models/scmod/ast/weapons/w_9mmarclip.mdl
models/scmod/ast/weapons/w_9mmclip.mdl
models/scmod/ast/weapons/w_9mmhandgun.mdl
models/scmod/ast/weapons/w_crowbar.mdl
models/scmod/ast/weapons/w_desert_eagle.mdl
models/scmod/ast/weapons/w_grenade.mdl
models/scmod/ast/weapons/w_m16.mdl
models/scmod/ast/weapons/w_m40a1.mdl
models/scmod/ast/weapons/w_mp5_clip.mdl
models/scmod/ast/weapons/w_saw.mdl
models/scmod/ast/weapons/w_saw_clip.mdl
models/scmod/mduty/apc_turret2.mdl
models/scmod/phouse/sky_clouds.mdl
models/scmod/phouse/sky_xen.mdl
models/scmod/sky/sky_xen2.mdl
sound/ast/apc.wav
sound/ast/dialogs/ast_c01/1sven_r.ogg
sound/ast/dialogs/ast_c01/introgrunt2.ogg
sound/ast/dialogs/ast_c01/introgrunt2a.ogg
sound/ast/dialogs/ast_c01/introgrunt2b.ogg
sound/ast/dialogs/ast_c01/introgrunt2c.ogg
sound/ast/forgetfreeman_morchkovalski_fix3.ogg
sound/ast/hev_nvg.ogg
sound/weapons/629_shells_land.wav
sound/weapons/cs/awp_clipin.wav
sound/weapons/cs/awp_clipout.wav
sound/weapons/cs/boltdown.wav
sound/weapons/cs/boltpull1.wav
sound/weapons/cs/boltup.wav
sound/weapons/knife_deploy1.wav
sound/weapons/m4_boltback.wav
sound/weapons/m4_boltrelease.wav
sound/weapons/m4_magin.wav
sound/weapons/m4_magout.wav
sound/weapons/revolvers_bulletsin.wav
sound/weapons/revolvers_rod.wav
sound/weapons/revolvers_wheelin.wav
sound/weapons/revolvers_wheelout.wav
sound/weapons/ump45_magin.wav
sound/weapons/ump45_magout.wav
sound/weapons/usp_drawcock.wav
sound/weapons/usp_magin.wav
sound/weapons/usp_magout.wav
sound/weapons/usp_pickup.wav
sound/weapons/usp_slideback.wav
sprites/opfor/weapon_knife.txt
